Repository infiniflow/infinity, pull requests merged in 2024-11, with the labels that each got.

#2142 Add test cases for cluster test
  python/infinity_http.py
  python/test_cluster/infinity_cluster.py
  python/test_cluster/test_basic.py
  python/test_cluster/test_insert.py
  tools/run_cluster_test.py
Labels: ci

#2144 Initial support for boolean similarity
  benchmark/local_infinity/fulltext/fulltext_benchmark.cpp
  benchmark/local_infinity/infinity_benchmark.cpp
  src/executor/operator/physical_match.cpp
  src/executor/operator/physical_match.cppm
  src/executor/physical_planner.cpp
  src/planner/bound_select_statement.cpp
  src/planner/node/logical_match.cppm
  src/planner/optimizer/index_scan/filter_expression_push_down_indexscanfilter.cpp
  src/planner/optimizer/index_scan/index_filter_evaluators.cpp
  src/planner/optimizer/index_scan/index_filter_evaluators.cppm
  src/storage/invertedindex/search/and_iterator.cpp
  src/storage/invertedindex/search/and_iterator.cppm
  src/storage/invertedindex/search/and_not_iterator.cpp
  src/storage/invertedindex/search/and_not_iterator.cppm
  src/storage/invertedindex/search/blockmax_wand_iterator.cppm
  src/storage/invertedindex/search/doc_iterator.cppm
  src/storage/invertedindex/search/filter_iterator.cpp
  src/storage/invertedindex/search/filter_iterator.cppm
  src/storage/invertedindex/search/minimum_should_match_iterator.cpp
  src/storage/invertedindex/search/minimum_should_match_iterator.cppm
  src/storage/invertedindex/search/or_iterator.cpp
  src/storage/invertedindex/search/or_iterator.cppm
  src/storage/invertedindex/search/parse_fulltext_options.cppm
  src/storage/invertedindex/search/phrase_doc_iterator.cpp
  src/storage/invertedindex/search/phrase_doc_iterator.cppm
  src/storage/invertedindex/search/query_builder.cpp
  src/storage/invertedindex/search/query_builder.cppm
  src/storage/invertedindex/search/query_node.cpp
  src/storage/invertedindex/search/query_node.h
  src/storage/invertedindex/search/query_node_module.cppm
  src/storage/invertedindex/search/score_threshold_iterator.cpp
  src/storage/invertedindex/search/score_threshold_iterator.cppm
  src/storage/invertedindex/search/term_doc_iterator.cpp
  src/storage/invertedindex/search/term_doc_iterator.cppm
  src/unit_test/storage/invertedindex/search/query_builder.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
  test/sql/dql/fulltext/fulltext_minimum_should_match.slt
Labels: ci

#2154 Fix bug of RAG analyzer
  src/common/analyzer/rag_analyzer.cpp
  src/common/analyzer/rag_analyzer.cppm
  src/unit_test/common/analyzer/rag_analyzer.cpp
Labels: ci

#2160 Fix data size
  src/executor/operator/physical_show.cpp
  src/storage/meta/entry/block_column_entry.cpp
  src/storage/meta/entry/block_column_entry.cppm
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/storage.cpp
Labels: ci

#2158 Fix bug: error when creating secondary index for only one value
  python/test_pysdk/test_index.py
  test/sql/dql/index_scan/index_scan_insert.slt
  third_party/pgm/include/pgm/piecewise_linear_model.hpp
Labels: ci

#2150 Fix error: when infinity failed to connect to minio, the infinity status is wrong.
  python/test_cluster/test_basic.py
  src/admin/admin_executor.cpp
  src/common/status.cpp
  src/common/status.cppm
  src/main/infinity_context.cpp
  src/storage/io/s3_client.cppm
  src/storage/io/s3_client_minio.cpp
  src/storage/io/s3_client_minio.cppm
  src/storage/io/virtual_store.cpp
  src/storage/io/virtual_store.cppm
  src/storage/storage.cpp
  src/storage/storage.cppm
Labels: ci

#2152 Fix check visibility when exporting.
  src/executor/operator/physical_export.cpp
  src/executor/operator/physical_export.cppm
  test/sql/dml/export/test_export_deleted.slt
  test/sql/dml/export/test_export_embedding.slt
Labels: ci

#2161 Update show block and segment info
  src/executor/operator/physical_show.cpp
  src/storage/definition/index_base.cpp
Labels: ci

#2149 Fix ci.
  .github/workflows/slow_test.yml
  .github/workflows/tests.yml
  python/test_cluster/conftest.py
  python/test_cluster/docker_infinity_cluster.py
  python/test_cluster/infinity_cluster.py
  python/test_cluster/mocked_infinity_cluster.py
  python/test_cluster/test_basic.py
  python/test_cluster/test_insert.py
  scripts/Dockerfile_infinity_tester_centos7
  scripts/build_tester_image.py
Labels: ci

#2162 Fix show segment
  python/test_cluster/README.md
  python/test_cluster/test_basic.py
  src/common/status.cpp
  src/common/status.cppm
  src/executor/operator/physical_show.cpp
  src/main/cluster_manager.cpp
  src/network/peer_thrift_client.cpp
  src/storage/meta/entry/segment_entry.cpp
  src/storage/meta/entry/segment_entry.cppm
Labels: ci

#2168 Support keyword analyzer
  src/common/analyzer/analyzer_pool.cpp
  src/common/analyzer/analyzer_pool.cppm
  src/common/analyzer/keyword_analyzer.cpp
  src/common/analyzer/keyword_analyzer.cppm
  src/parser/search_parser.cpp
  src/parser/search_parser.y
  src/storage/invertedindex/search/doc_iterator.cppm
  src/storage/invertedindex/search/keyword_iterator.cppm
  src/storage/invertedindex/search/query_node.cpp
  src/storage/invertedindex/search/query_node.h
  src/storage/invertedindex/search/search_driver.cpp
  src/storage/invertedindex/search/search_driver.h
  test/sql/dql/fulltext/fulltext_keyword.slt
Labels: ci

#2166 Add cluster test cases
  conf/learner2.toml
  python/infinity_http.py
  python/test_cluster/common_values.py
  python/test_cluster/conftest.py
  python/test_cluster/docker_infinity_cluster.py
  python/test_cluster/infinity_cluster.py
  python/test_cluster/requirements.txt
  python/test_cluster/test_basic.py
  python/test_cluster/test_database.py
  python/test_cluster/test_delete.py
  python/test_cluster/test_export.py
  python/test_cluster/test_import.py
  python/test_cluster/test_index.py
  python/test_cluster/test_insert.py
  python/test_cluster/test_knn.py
  python/test_cluster/test_select.py
  python/test_cluster/test_table.py
  python/test_cluster/test_update.py
  scripts/build_tester_image.py
  src/common/utility/exception.cpp
  src/main/cluster_manager.cpp
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
Labels: ci

#2171 Refactor cache result config
  conf/infinity_conf.toml
  conf/pytest_parallel_continuous_conf.toml
  conf/pytest_parallel_infinity_conf.toml
  conf/pytest_parallel_infinity_follower.toml
  conf/pytest_parallel_infinity_leader.toml
  conf/pytest_parallel_infinity_minio.toml
  conf/pytest_parallel_infinity_vfs_off.toml
  docs/references/configurations.mdx
  python/parallel_test/test_index_parallel.py
  python/test_pysdk/test_knn.py
  src/common/default_values.cppm
  src/executor/operator/physical_command.cpp
  src/main/config.cpp
  src/main/config.cppm
  src/main/infinity_context.cpp
  src/main/infinity_context.cppm
  src/main/options.cpp
  src/main/options.cppm
  src/storage/storage.cpp
  src/unit_test/main/config.cpp
  test/data/config/infinity_conf.toml
  test/sql/dql/filter/filter_fulltext_function.slt
  test/sql/dql/index_scan/index_scan_str.slt
  test/sql/dql/knn/tensor/fusion_rerank_maxsim.slt
Labels: ci

#2173 Update keyword support
  src/storage/invertedindex/search/doc_iterator.cppm
  src/storage/invertedindex/search/filter_iterator.cpp
  src/storage/invertedindex/search/filter_iterator.cppm
  src/storage/invertedindex/search/keyword_iterator.cppm
  src/storage/invertedindex/search/must_first_iterator.cppm
  src/storage/invertedindex/search/query_node.cpp
  src/storage/invertedindex/search/query_node.h
  src/storage/invertedindex/search/search_driver.cpp
  src/unit_test/storage/invertedindex/search/query_builder.cpp
  test/sql/dql/fulltext/fulltext_keyword.slt
Labels: ci

#2177 Improve performance of RAG tokenizer
  src/common/analyzer/rag_analyzer.cpp
  src/common/analyzer/rag_analyzer.cppm
  src/storage/invertedindex/memory_indexer.cpp
Labels: ci

#2176 Refactor: Remove TXN context
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/storage/txn/txn_context.cppm
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
Labels: ci

#2179 Refactor function name
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
Labels: ci

#2180 Fix initialize compact data.
  src/function/table/compact_state_data.cppm
  src/storage/meta/entry/table_index_entry.cpp
Labels: ci

#2178 Add log
  python/parallel_test/conftest.py
  python/parallel_test/test_ddl_parallel.py
  python/parallel_test/test_index_parallel.py
  scripts/collect_cluster_log.py
  scripts/collect_log.py
  scripts/timeout_kill.py
  src/executor/operator/physical_show.cpp
  src/storage/meta/entry/db_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/storage.cpp
  src/storage/txn/txn.cpp
  src/storage/wal/catalog_delta_entry.cpp
  src/storage/wal/catalog_delta_entry.cppm
  src/storage/wal/wal_entry.cpp
Labels: ci

#2185 Update tests
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/parallel_test/test_index_parallel.py
  src/main/infinity_context.cpp
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  src/storage/column_vector/column_vector.cppm
  test/sql/ddl/schema/use_schema.slt
Labels: ci

#2184 Fix learner can switch to leader issue
  src/admin/admin_executor.cpp
  src/common/status.cpp
  src/common/status.cppm
  src/main/infinity_context.cpp
Labels: ci

#2186 Fix concurrent issue, in cluster admin
  src/admin/admin_executor.cpp
  src/executor/operator/physical_show.cpp
  src/main/cluster_manager.cpp
  src/main/cluster_manager.cppm
  src/network/peer_server_thrift_service.cpp
Labels: ci

#2190 Cache config http
  python/infinity_http.py
  python/test_pysdk/conftest.py
  python/test_pysdk/test_show.py
  src/executor/operator/physical_command.cpp
  src/executor/operator/physical_show.cpp
  src/main/cluster_manager.cpp
  test/sql/config/cache_config.slt
Labels: ci

#2187 Cluster manager: remove set storage ptr on construction
  src/admin/admin_executor.cpp
  src/executor/operator/physical_show.cpp
  src/main/cluster_manager.cpp
  src/main/cluster_manager.cppm
  src/main/infinity_context.cpp
  src/network/node_info.cpp
  src/network/node_info.cppm
  src/network/peer_server_thrift_service.cpp
  src/network/peer_task.cpp
  src/network/peer_task.cppm
  src/network/peer_thrift_client.cpp
  src/storage/definition/index_base.cppm
  test/sql/config/cache_config.slt
Labels: ci

#2197 Fix data race in buffer manager
  src/storage/buffer/buffer_manager.cppm
Labels: ci

#2200 Fix another data race on PhysicalLimit
  src/admin/admin_executor.cpp
  src/executor/operator/physical_limit.cppm
Labels: ci

#2205 Fix fulltext search parser
  src/parser/search_parser.cpp
  src/parser/search_parser.y
  src/storage/invertedindex/search/search_driver.cpp
  test/sql/dql/fulltext/fulltext_delete.slt
  test/sql/dql/fulltext/fulltext_keyword.slt
Labels: ci

#2209 Fix data race1
  CMakeLists.txt
  conf/pytest_parallel_infinity_conf.toml
  python/parallel_test/test_index_parallel.py
  python/parallel_test/util.py
  src/executor/operator/physical_scan/physical_knn_scan.cpp
  src/storage/invertedindex/memory_indexer.cpp
  src/storage/knn_index/knn_hnsw/abstract_hnsw.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/meta/entry/table_index_entry.cppm
Labels: ci

#2210 Update ObjectCount
  src/common/stl.cppm
  src/network/pg_server.cpp
  src/network/pg_server.cppm
  src/network/ring_buffer_iterator.cppm
  src/storage/definition/index_base.cppm
Labels: ci

#2208 Python API updates
  docs/references/configurations.mdx
  docs/references/http_api_reference.mdx
  docs/references/pysdk_api_reference.md
  python/infinity_embedded/local_infinity/client.py
  python/infinity_embedded/local_infinity/infinity.py
  python/infinity_http.py
  python/infinity_sdk/infinity/infinity.py
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/infinity/remote_thrift/infinity.py
  python/infinity_sdk/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py
  python/infinity_sdk/infinity/remote_thrift/infinity_thrift_rpc/constants.py
  python/infinity_sdk/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/test_pysdk/test_delete.py
  python/test_pysdk/test_show.py
  scripts/Dockerfile_infinity
  src/embedded_infinity/wrap_infinity.cpp
  src/embedded_infinity/wrap_infinity.cppm
  src/embedded_infinity_ext.cpp
  src/main/config.cpp
  src/network/http_server.cpp
  src/network/infinity_thrift/InfinityService.cpp
  src/network/infinity_thrift/InfinityService.h
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  src/network/infinity_thrift_types.cppm
  src/unit_test/main/config.cpp
  thrift/infinity.thrift
Labels: ci

#2213 Implement admin show delta catalog
  src/admin/admin_executor.cpp
  src/admin/admin_executor.cppm
  src/main/infinity_context.cpp
  src/storage/meta/catalog.cppm
Labels: ci

#2214 Update version info to 0.5.0-dev2
  README.md
  benchmark/remote_infinity/remote_query_benchmark.cpp
  client/cpp/infinity_client.cpp
  docs/getstarted/build_from_source.mdx
  docs/getstarted/deploy_infinity_server.mdx
  docs/getstarted/quickstart.md
  pyproject.toml
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/pyproject.toml
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
Labels: ci

#2211 Fix add chunk entry checkpoint.
  src/storage/meta/entry/segment_index_entry.cppm
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/wal/catalog_delta_entry.cpp
Labels: ci

#2218 Adjust latin tokenizer within RAG analyzer
  src/common/analyzer/rag_analyzer.cpp
  src/common/analyzer/rag_analyzer.cppm
Labels: ci

#2219 Fix test and config
  conf/pytest_parallel_infinity_conf.toml
  test/sql/config/cache_config.slt
Labels: ci

#2228 Fix NLTK tokenizer within RAG analyzer
  src/common/analyzer/rag_analyzer.cpp
Labels: ci

#2229 Fix bugs
  .github/workflows/tests.yml
  benchmark/local_infinity/knn/knn_import_benchmark.cpp
  benchmark/local_infinity/knn/knn_query_benchmark.cpp
  conf/pytest_embedded_infinity_conf.toml
  python/infinity_embedded/__init__.py
  python/infinity_embedded/common.py
  python/infinity_embedded/local_infinity/client.py
  python/infinity_embedded/local_infinity/infinity.py
  python/infinity_sdk/infinity/remote_thrift/infinity.py
  python/restart_test/test_memidx.py
  scripts/collect_embedded_log.py
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/storage/io/object_storage_process.cpp
  src/storage/io/object_storage_task.cppm
  src/storage/io/virtual_store.cpp
  src/storage/io/virtual_store.cppm
  src/storage/persistence/persist_result_handler.cpp
  src/storage/txn/txn.cpp
Labels: ci

#2231 Fix rag analyzer
  src/common/analyzer/rag_analyzer.cpp
Labels: ci

#2221 Fix data race3
  src/executor/operator/physical_compact.cpp
  src/executor/operator/physical_compact_index_do.cpp
  src/executor/operator/physical_export.cpp
  src/executor/operator/physical_import.cpp
  src/executor/operator/physical_match.cpp
  src/executor/operator/physical_scan/physical_knn_scan.cpp
  src/executor/operator/physical_scan/physical_match_sparse_scan.cpp
  src/executor/operator/physical_scan/physical_match_tensor_scan.cpp
  src/executor/operator/physical_scan/physical_scan_base.cpp
  src/executor/operator/physical_scan/physical_table_scan.cpp
  src/executor/physical_operator.cpp
  src/function/table/compact_state_data.cpp
  src/function/table/compact_state_data.cppm
  src/storage/bg_task/segment_sealing_tasks/build_fast_rough_filter_task.cpp
  src/storage/invertedindex/column_index_reader.cpp
  src/storage/invertedindex/column_index_reader.cppm
  src/storage/knn_index/emvb/emvb_index.cpp
  src/storage/knn_index/emvb/emvb_index_in_mem.cpp
  src/storage/knn_index/emvb/emvb_index_in_mem.cppm
  src/storage/knn_index/knn_hnsw/abstract_hnsw.cppm
  src/storage/knn_index/knn_hnsw/hnsw_alg.cppm
  src/storage/knn_index/knn_ivf/ivf_index_data.cpp
  src/storage/knn_index/knn_ivf/ivf_index_data_in_mem.cpp
  src/storage/knn_index/sparse/bp_reordering.cppm
  src/storage/meta/entry/block_column_entry.cpp
  src/storage/meta/entry/block_column_entry.cppm
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/meta/entry/table_index_entry.cppm
  src/storage/meta/iter/block_column_iter.cppm
  src/storage/meta/iter/block_iter.cppm
  src/storage/secondary_index/common_query_filter.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/unit_test/storage/bg_task/cleanup_task.cpp
  src/unit_test/storage/buffer/buffer_obj.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
  src/unit_test/storage/meta/entry/table_entry.cpp
  src/unit_test/storage/wal/catalog_delta_replay.cpp
  src/unit_test/storage/wal/repeat_replay.cpp
  src/unit_test/storage/wal/wal_replay.cpp
Labels: ci

#2224 Refactor cluster mgr
  src/admin/admin_executor.cpp
  src/main/cluster_manager.cpp
  src/main/cluster_manager.cppm
  src/main/cluster_manager_admin.cpp
  src/main/cluster_manager_standalone.cpp
  src/main/infinity_context.cpp
  src/main/infinity_context.cppm
  src/main/logger.cpp
  src/main/logger.cppm
  src/network/peer_server_thrift_service.cpp
  src/scheduler/task_scheduler.cpp
  src/storage/background_process.cpp
  src/storage/compaction_process.cpp
  src/storage/io/s3_client_minio.cpp
  src/storage/io/virtual_store.cpp
  src/storage/io/virtual_store.cppm
  src/storage/storage.cpp
  src/storage/storage.cppm
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
  src/unit_test/main/stats/global_resource_usage.cpp
Labels: ci

#2236 Index hint
  src/executor/operator/physical_match.cpp
  src/executor/operator/physical_scan/physical_match_sparse_scan.cpp
  src/executor/operator/physical_scan/physical_match_tensor_scan.cpp
  src/expression/match_expression.cpp
  src/expression/match_expression.cppm
  src/expression/match_sparse_expression.cpp
  src/expression/match_sparse_expression.cppm
  src/expression/match_tensor_expression.cpp
  src/expression/match_tensor_expression.cppm
  src/parser/expr/match_expr.cpp
  src/parser/expr/match_expr.h
  src/parser/expr/match_tensor_expr.h
  src/parser/expr/parsed_expr.h
  src/parser/parser.cpp
  src/parser/parser.y
  src/planner/bound_select_statement.cpp
  src/planner/expression_binder.cpp
  src/planner/optimizer/index_scan/filter_expression_push_down_indexscanfilter.cpp
  src/planner/optimizer/index_scan/index_filter_evaluators.cpp
  src/planner/optimizer/index_scan/index_filter_evaluators.cppm
  src/storage/invertedindex/column_index_reader.cpp
  src/storage/invertedindex/column_index_reader.cppm
  src/storage/invertedindex/search/query_builder.cpp
  src/storage/invertedindex/search/query_builder.cppm
  src/storage/invertedindex/search/query_node.cpp
  src/storage/invertedindex/search/query_node.h
  src/unit_test/storage/invertedindex/search/query_builder.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
  test/sql/dql/filter/filter_fulltext_function.slt
  test/sql/dql/fulltext/fulltext.slt
  test/sql/dql/knn/sparse/test_knn_sparse_bmp.slt
Labels: ci

#2241 Refactor storage
  src/storage/storage.cpp
  src/storage/storage.cppm
Labels: ci

#2242 Refactor storage admin->writer
  src/storage/storage.cpp
  src/storage/storage.cppm
Labels: ci

#2232 Update rag analyzer
  src/common/analyzer/darts_trie.cpp
  src/common/analyzer/darts_trie.cppm
  src/common/analyzer/rag_analyzer.cpp
  src/common/analyzer/rag_analyzer.cppm
  src/common/analyzer/string_utils.h
Labels: ci

#2233 Fix cluster datarace
  .github/workflows/slow_test.yml
  .tester_env
  python/restart_test/test_memidx.py
  scripts/collect_cluster_log.py
  scripts/collect_log.py
  scripts/collect_restart_log.py
  scripts/collect_thread_sanitizer_log.py
  src/bin/infinity_main.cpp
  src/main/cluster_manager.cpp
  src/network/http_server.cpp
  src/network/http_server.cppm
  src/network/peer_thrift_client.cpp
  src/network/peer_thrift_client.cppm
  src/network/peer_thrift_server.cpp
  src/network/peer_thrift_server.cppm
  src/network/pg_server.cpp
  src/network/pg_server.cppm
  src/network/thrift_server.cpp
  src/network/thrift_server.cppm
  src/storage/meta/entry/entry_list.cppm
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
  tools/run_restart_test.py
Labels: ci, slow-test

#2243 Update reader->admin
  src/storage/storage.cpp
Labels: ci

#2244 Fix admin show catalogs
  src/admin/admin_executor.cpp
  src/storage/io/virtual_store.cpp
  src/storage/io/virtual_store.cppm
  src/storage/storage.cpp
Labels: ci

#2249 Update rag analyzer
  src/common/analyzer/rag_analyzer.cpp
  src/common/analyzer/rag_analyzer.cppm
Labels: ci

#2245 Index hint SDK and HTTP APIs
  docs/references/http_api_reference.mdx
  docs/references/pysdk_api_reference.md
  python/test_pysdk/test_knn.py
  src/embedded_infinity/wrap_infinity.cpp
  src/expression/match_expression.cpp
  src/expression/match_sparse_expression.cpp
  src/expression/match_tensor_expression.cpp
  src/network/http/http_search.cpp
  src/network/infinity_thrift_service.cpp
  test/sql/dql/result_cache/cached_sparse_scan.slt
Labels: documentation, ci

#2248 Refactor reader->writer
  src/storage/storage.cpp
  src/storage/storage.cppm
Labels: ci

#2254 Fix fulltext search parser again. Close #2251
  src/parser/expression_lexer.cpp
  src/parser/expression_lexer.h
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/search_lexer.cpp
  src/parser/search_lexer_plain.cpp
  src/parser/search_parser.cpp
  src/parser/search_parser.y
  src/unit_test/parser/search_driver.cpp
Labels: ci

#2247 Fix memidx dump
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/infinity/remote_thrift/infinity.py
  python/infinity_sdk/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py
  python/infinity_sdk/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/restart_test/test_memidx.py
  src/admin/admin_executor.cpp
  src/executor/explain_physical_plan.cpp
  src/executor/operator/physical_command.cpp
  src/executor/operator/physical_flush.cpp
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/main/infinity_context.cpp
  src/network/infinity_thrift/InfinityService.cpp
  src/network/infinity_thrift/InfinityService.h
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  src/network/infinity_thrift_types.cppm
  src/parser/statement/command_statement.cpp
  src/parser/statement/command_statement.cppm
  src/parser/statement/command_statement.h
  src/parser/statement/flush_statement.h
  src/planner/explain_ast.cpp
  src/planner/explain_logical_plan.cpp
  src/planner/logical_planner.cpp
  src/planner/logical_planner.cppm
  src/planner/node/logical_command.cpp
  src/planner/node/logical_flush.cpp
  src/storage/bg_task/bg_task.cpp
  src/storage/bg_task/bg_task.cppm
  src/storage/compaction_process.cpp
  src/storage/compaction_process.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  test/data/config/restart_test/test_memidx/5.toml
  thrift/infinity.thrift
Labels: ci

#2253 Refactor writer->admin
  src/storage/storage.cpp
  src/storage/storage.cppm
Labels: ci

#2255 Update version info to 0.5.0.dev3
  README.md
  benchmark/remote_infinity/remote_query_benchmark.cpp
  client/cpp/infinity_client.cpp
  docs/getstarted/build_from_source.mdx
  docs/getstarted/deploy_infinity_server.mdx
  docs/getstarted/quickstart.md
  pyproject.toml
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/pyproject.toml
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
Labels: ci

#2256 Refactor: writer->reader
  src/storage/storage.cpp
Labels: ci

#2257 Refactor storage: writer->un-init
  src/storage/storage.cpp
Labels: ci

#2259 Fix error node status
  src/main/cluster_manager.cpp
Labels: ci

#2260 Refactor cluster manager
  src/main/cluster_manager.cpp
  src/main/cluster_manager_leader.cpp
  src/main/cluster_manager_reader.cpp
Labels: ci

#2261 Refactor: print logs before infinity initialized
  src/bin/infinity_main.cpp
  src/main/infinity_context.cpp
Labels: ci

#2264 Start network server before storage is started
  python/infinity_sdk/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/restart_test/test_memidx.py
  src/admin/admin_executor.cpp
  src/bin/infinity_main.cpp
  src/common/status.cpp
  src/common/status.cppm
  src/main/infinity.cpp
  src/main/infinity_context.cpp
  src/main/infinity_context.cppm
  src/main/query_context.cpp
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/unit_test/base_test.cppm
  src/unit_test/executor/pipeline/fragment.cpp
  src/unit_test/main/query_profiler.cpp
  src/unit_test/storage/bg_task/compact_segments_task.cpp
  src/unit_test/storage/binary_fuse_filter/segment_sealing.cpp
  src/unit_test/storage/buffer/buffer_obj.cpp
  src/unit_test/storage/io/virtual_store.cpp
  src/unit_test/storage/txn/conflict_check.cpp
  src/unit_test/storage/wal/catalog_delta_replay.cpp
  src/unit_test/storage/wal/checkpoint.cpp
  src/unit_test/storage/wal/recycle_log.cpp
  src/unit_test/storage/wal/repeat_replay.cpp
  src/unit_test/storage/wal/wal_entry.cpp
  src/unit_test/storage/wal/wal_replay.cpp
  thrift/infinity.thrift
Labels: ci

#2263 Fix.
  .github/workflows/slow_test.yml
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/restart_test/test_insert.py
  python/restart_test/test_memidx.py
  python/restart_test/util.py
  scripts/collect_thread_sanitizer_log.py
  scripts/prepare_restart_test_data.py
  scripts/sanitizer_filter.py
  src/main/cluster_manager_leader.cpp
  src/scheduler/fragment_task.cpp
  src/storage/bg_task/periodic_trigger.cpp
  src/storage/bg_task/periodic_trigger.cppm
  src/storage/buffer/buffer_obj.cpp
  src/storage/invertedindex/memory_indexer.cppm
  src/storage/meta/catalog.cpp
  src/storage/wal/catalog_delta_entry.cpp
  src/storage/wal/catalog_delta_entry.cppm
  src/unit_test/storage/wal/catalog_delta_entry.cpp
  test/data/config/restart_test/test_fulltext/1.toml
  test/data/config/restart_test/test_fulltext/2.toml
  test/data/config/restart_test/test_fulltext/3.toml
  test/data/config/restart_test/test_insert/6.toml
  tools/run_restart_test_continuously.py
Labels: ci, slow-test

#2268 Fix memory leak
  src/common/analyzer/tokenizer.cpp
  src/common/analyzer/tokenizer.cppm
Labels: ci

#2267 Fix infinity connect in test.
  python/infinity_embedded/errors.py
  python/infinity_http.py
  python/infinity_sdk/infinity/errors.py
  python/restart_test/infinity_runner.py
  python/restart_test/test_insert.py
  python/test_cluster/docker_infinity_cluster.py
  python/test_cluster/infinity_cluster.py
  src/common/status.cpp
  src/common/status.cppm
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/main/infinity_context.cpp
  src/main/infinity_context.cppm
  src/main/query_context.cpp
  src/main/query_result.cppm
Labels: ci, slow-test

#2271 Fix sort expression
  python/infinity_embedded/local_infinity/query_builder.py
  python/infinity_embedded/local_infinity/table.py
  python/infinity_sdk/infinity/remote_thrift/query_builder.py
  python/infinity_sdk/infinity/remote_thrift/table.py
Labels: ci

#2265 Update version info to 0.5.0-dev4
  README.md
  benchmark/remote_infinity/remote_query_benchmark.cpp
  client/cpp/infinity_client.cpp
  docs/getstarted/build_from_source.mdx
  docs/getstarted/deploy_infinity_server.mdx
  docs/getstarted/quickstart.md
  pyproject.toml
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/pyproject.toml
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
Labels: ci

#2273 Update rag_analyzer.cpp
  src/common/analyzer/rag_analyzer.cpp
Labels: ci

#2276 Fix bugs
  example/show_node.py
  python/infinity_embedded/local_infinity/query_builder.py
  python/infinity_sdk/infinity/remote_thrift/query_builder.py
  src/main/query_context.cpp
  src/network/infinity_thrift_service.cpp
Labels: ci

#2266 Update cluster test to run single case
  python/test_cluster/README.md
  tools/run_cluster_test.py
Labels: ci

#2275 add cluster test: single node and cluster member change
  python/test_cluster/database_operations.py
  python/test_cluster/test_member_change.py
  python/test_cluster/test_single_node.py
Labels: ci

#2281 Fix bugs
  src/network/peer_server_thrift_service.cpp
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
  tools/run_cluster_test.py
Labels: ci

#2274 Fix slow test
  .github/workflows/slow_test.yml
  python/infinity_sdk/infinity/__init__.py
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/infinity/remote_thrift/infinity.py
  python/infinity_sdk/pyproject.toml
  python/restart_test/infinity_runner.py
  python/restart_test/restart_util.py
  python/restart_test/test_fulltext.py
  python/restart_test/test_insert.py
  python/restart_test/test_insert_import.py
  python/restart_test/test_shutdown_pytest.py
  python/test_pysdk/test_database.py
  scripts/collect_restart_log.py
  scripts/prepare_restart_test_data.py
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/txn/txn.cpp
  tools/run_restart_test.py
Labels: ci

#2282 Update PhysicalImport::ImportPARQUET
  src/common/third_party.cppm
  src/executor/operator/physical_import.cpp
Labels: ci

#2284 Fix bug in filter
  src/planner/optimizer/index_scan/filter_expression_push_down_fastroughfilter.cpp
Labels: ci

#2278 More cluster test cases
  example/http/cluster_admin.sh
  python/infinity_http.py
  python/test_cluster/conftest.py
  python/test_cluster/test_admin.py
  src/network/http_server.cpp
Labels: ci

#2285 Fix PhysicalExport
  src/executor/operator/physical_export.cpp
  src/executor/operator/physical_export.cppm
Labels: ci

#2286 Cluster test3
  python/infinity_http.py
  python/parallel_test/conftest.py
  python/restart_test/infinity_runner.py
  python/test_cluster/conftest.py
  python/test_cluster/database_operations.py
  python/test_cluster/infinity_cluster.py
  python/test_cluster/mocked_infinity_cluster.py
  python/test_cluster/test_admin.py
  python/test_cluster/test_basic.py
  python/test_cluster/test_cluster_roles.py
  python/test_cluster/test_database.py
  python/test_cluster/test_delete.py
  python/test_cluster/test_export.py
  python/test_cluster/test_import.py
  python/test_cluster/test_index.py
  python/test_cluster/test_insert.py
  python/test_cluster/test_knn.py
  python/test_cluster/test_member_change.py
  python/test_cluster/test_select.py
  python/test_cluster/test_single_node.py
  python/test_cluster/test_table.py
  python/test_cluster/test_tc.py
  python/test_cluster/test_update.py
  scripts/collect_cluster_log.py
  scripts/timeout_kill.py
Labels: ci

#2291 Print message to notify user: infinity server is started
  src/main/infinity_context.cpp
Labels: ci

#2289 Cluster test
  python/infinity_http.py
  python/test_cluster/database_operations.py
  python/test_cluster/test_cluster_roles.py
  python/test_cluster/test_member_change.py
  python/test_cluster/test_single_node.py
Labels: ci

#2297 Add Hash() and Eq() support for InExpression
  src/expression/in_expression.cpp
  src/expression/in_expression.cppm
Labels: ci

#2298 Fix issue 2290
  src/storage/meta/cleanup_scanner.cpp
  src/storage/meta/cleanup_scanner.cppm
Labels: ci

#2300 Fix alter table lose index.
  python/restart_test/test_alter.py
  src/storage/meta/cleanup_scanner.cpp
  src/storage/meta/entry/chunk_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
  src/storage/txn/txn.cpp
  test/data/config/restart_test/test_alter/1.toml
  test/sql/ddl/alter/drop_column_with_index.slt
Labels: ci

#2303 Peer retry option
  conf/follower.toml
  conf/leader.toml
  conf/learner.toml
  conf/learner2.toml
  python/test_cluster/conftest.py
  python/test_cluster/infinity_cluster.py
  python/test_cluster/mocked_infinity_cluster.py
  python/test_cluster/test_basic.py
  src/common/default_values.cppm
  src/executor/operator/physical_show.cpp
  src/main/config.cpp
  src/main/config.cppm
  src/main/options.cpp
  src/main/options.cppm
  src/network/peer_thrift_client.cpp
  src/network/peer_thrift_client.cppm
  src/unit_test/main/config.cpp
  test/data/config/infinity_conf.toml
  test/data/config/test_conf_valid_value.toml
  tools/run_cluster_test.py
Labels: ci

#2306 Update IK analyzer
  src/common/analyzer/ik/analyze_context.cpp
  src/common/analyzer/ik/analyze_context.cppm
  src/common/analyzer/ik/arbitrator.cpp
  src/common/analyzer/ik/arbitrator.cppm
  src/common/analyzer/ik/character_util.cppm
  src/common/analyzer/ik/cjk_segmenter.cpp
  src/common/analyzer/ik/cjk_segmenter.cppm
  src/common/analyzer/ik/cn_quantifier_segmenter.cpp
  src/common/analyzer/ik/cn_quantifier_segmenter.cppm
  src/common/analyzer/ik/dict.cpp
  src/common/analyzer/ik/dict.cppm
  src/common/analyzer/ik/dict_segment.cpp
  src/common/analyzer/ik/dict_segment.cppm
  src/common/analyzer/ik/hit.cpp
  src/common/analyzer/ik/hit.cppm
  src/common/analyzer/ik/ik_analyzer.cpp
  src/common/analyzer/ik/ik_analyzer.cppm
  src/common/analyzer/ik/ik_segmenter.cpp
  src/common/analyzer/ik/ik_segmenter.cppm
  src/common/analyzer/ik/lexeme.cpp
  src/common/analyzer/ik/quick_sort_set.cpp
  src/common/analyzer/ik/quick_sort_set.cppm
  src/unit_test/common/analyzer/ik_analyzer.cpp
Labels: ci

#2307 ivf index dump by memory usage
  src/storage/compaction_process.cpp
  src/storage/knn_index/knn_ivf/ivf_index_data_in_mem.cpp
  src/storage/knn_index/knn_ivf/ivf_index_data_in_mem.cppm
  src/storage/knn_index/knn_ivf/ivf_index_storage.cpp
  src/storage/knn_index/knn_ivf/ivf_index_storage.cppm
  src/storage/knn_index/knn_ivf/ivf_index_storage_parts.cpp
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/tracer/memindex_tracer.cppm
Labels: ci

#2308 Python SDK didn't convert filter expression to lower case
  python/infinity_embedded/local_infinity/utils.py
  python/infinity_sdk/infinity/remote_thrift/utils.py
Labels: ci
