Repository infiniflow/infinity, pull requests merged in 2024-06, with the labels that each got.

#1270 fulltext Share PostingFormat among PostingWriters
  docs/getstarted/build_from_source.md
  scripts/Dockerfile_infinity_builder_centos7
  scripts/Dockerfile_infinity_builder_opencloudos
  scripts/Dockerfile_infinity_builder_ubuntu2310
  scripts/download_deps_infinity_builder_centos7.sh
  scripts/infinity-deps-ubuntu2004.sh
  scripts/infinity-deps-ubuntu2204.sh
  src/storage/invertedindex/format/doc_list_encoder.cpp
  src/storage/invertedindex/format/doc_list_encoder.cppm
  src/storage/invertedindex/format/doc_list_format_option.cppm
  src/storage/invertedindex/format/position_list_format_option.cppm
  src/storage/invertedindex/format/posting_list_format.cppm
  src/storage/invertedindex/memory_indexer.cpp
  src/storage/invertedindex/memory_indexer.cppm
  src/storage/invertedindex/posting_merger.cpp
  src/storage/invertedindex/posting_merger.cppm
  src/storage/invertedindex/posting_writer.cpp
  src/storage/invertedindex/posting_writer.cppm
  src/storage/meta/entry/table_entry.cpp
  src/unit_test/storage/invertedindex/column_inverter.cpp
  src/unit_test/storage/invertedindex/format/inmem_doc_list_decoder.cpp
  src/unit_test/storage/invertedindex/format/posting_byte_slice.cpp
  src/unit_test/storage/invertedindex/format/posting_byte_slice_reader.cpp
  src/unit_test/storage/invertedindex/posting_writer.cpp
Labels: ci

#1273 Add new command: show index segment info
  src/executor/explain_physical_plan.cpp
  src/executor/operator/physical_show.cpp
  src/executor/operator/physical_show.cppm
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/statement/show_statement.cpp
  src/parser/statement/show_statement.h
  src/planner/explain_ast.cpp
  src/planner/explain_logical_plan.cpp
  src/planner/logical_planner.cpp
  src/planner/logical_planner.cppm
  src/planner/node/logical_show.cpp
  src/planner/node/logical_show.cppm
Labels: ci

#1275 Add new command: show index chunk info
  docs/references/http_api_reference.md
  python/infinity/errors.py
  src/common/status.cpp
  src/common/status.cppm
  src/executor/explain_physical_plan.cpp
  src/executor/operator/physical_show.cpp
  src/executor/operator/physical_show.cppm
  src/executor/physical_planner.cpp
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/network/http_server.cpp
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/lexer.l
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser.y
  src/parser/statement/show_statement.cpp
  src/parser/statement/show_statement.h
  src/planner/explain_ast.cpp
  src/planner/explain_logical_plan.cpp
  src/planner/logical_planner.cpp
  src/planner/logical_planner.cppm
  src/planner/node/logical_show.cpp
  src/planner/node/logical_show.cppm
Labels: ci

#1277 Fix redundant code
  src/main/query_context.cpp
Labels: ci

#1278 Fix missing first_delete_ts_
  src/storage/meta/catalog.cpp
  src/storage/meta/entry/segment_entry.cpp
  src/storage/meta/entry/segment_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/wal/catalog_delta_entry.cpp
  src/storage/wal/catalog_delta_entry.cppm
  src/storage/wal/wal_manager.cpp
  test/data/csv/fulltext_delete.csv
  test/sql/dql/fulltext/fulltext.slt
  test/sql/dql/fulltext/fulltext_delete.slt
Labels: ci

#1280 Refactor code
  README.md
  python/README.md
  python/infinity/remote_thrift/client.py
  python/infinity/remote_thrift/table.py
  python/pyproject.toml
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
Labels: ci

#1284 Add python example for ColBERT reranker
  example/ColBERT_reranker_example/helper.py
  example/ColBERT_reranker_example/test_helper.py
Labels: ci

#1288 Added rrf window_size
  src/common/stl.cppm
  src/executor/operator/physical_fusion.cpp
  test/sql/dql/fusion.slt
Labels: ci

#1289 Multiway fusion
  python/benchmark/preprocess_tantivy_queries.py
  src/executor/fragment_builder.cpp
  src/executor/operator/physical_fusion.cpp
  src/executor/operator/physical_fusion.cppm
  src/executor/physical_planner.cpp
  src/planner/bound_select_statement.cpp
  src/planner/node/logical_fusion.cppm
  test/sql/dql/fusion.slt
Labels: ci

#1290 Add three global variables
  src/common/default_values.cppm
  src/executor/operator/physical_command.cpp
  src/executor/operator/physical_show.cpp
  src/main/query_context.cppm
  src/main/session.cppm
  src/main/variables.cpp
  src/main/variables.cppm
  src/storage/background_process.cpp
  src/storage/background_process.cppm
  src/storage/compaction_process.cpp
  src/storage/compaction_process.cppm
Labels: ci

#1285 Refactor physical match
  src/executor/operator/physical_flush.cpp
  src/executor/operator/physical_match.cpp
  src/executor/operator/physical_match.cppm
  src/executor/physical_planner.cpp
  src/planner/bound_select_statement.cpp
  src/planner/node/logical_match.cppm
  src/storage/invertedindex/search/early_terminate_iterator/early_terminate_iterator.cppm
  src/storage/invertedindex/search/query_builder.cpp
  src/storage/invertedindex/search/query_builder.cppm
  src/storage/invertedindex/search/query_node.cpp
  src/storage/invertedindex/search/query_node.h
  src/unit_test/storage/invertedindex/search/query_builder.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
Labels: ci

#1291 Fix read file function
  src/storage/io/local_file_system.cpp
  src/unit_test/storage/invertedindex/column_index_merger.cpp
  src/unit_test/storage/invertedindex/format/term_meta.cpp
  src/unit_test/storage/invertedindex/memory_indexer.cpp
Labels: ci

#1293 Fix export embedding to wrong json type
  src/executor/operator/physical_import.cpp
  src/storage/column_vector/value.cpp
  test/sql/dml/import/test_export_embedding.slt
Labels: ci

#1294 [Bug] Fix import jsonl and json file, row count zero
  src/executor/operator/physical_import.cpp
Labels: ci

#1296 Purge bad entries after latest checkpoint
  src/storage/io/local_file_system.cpp
  src/storage/io/local_file_system.cppm
  src/storage/wal/wal_entry.cpp
  src/storage/wal/wal_entry.cppm
  src/storage/wal/wal_manager.cpp
  src/unit_test/storage/wal/wal_entry.cpp
Labels: ci

#1299 Add show buffer command
  src/CMakeLists.txt
  src/executor/explain_physical_plan.cpp
  src/executor/operator/physical_show.cpp
  src/executor/operator/physical_show.cppm
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/statement/show_statement.cpp
  src/parser/statement/show_statement.h
  src/planner/explain_ast.cpp
  src/planner/explain_logical_plan.cpp
  src/planner/logical_planner.cpp
  src/planner/logical_planner.cppm
  src/planner/node/logical_show.cpp
  src/planner/node/logical_show.cppm
  src/storage/buffer/buffer_manager.cpp
  src/storage/buffer/buffer_manager.cppm
  src/storage/buffer/buffer_obj.cppm
  src/storage/buffer/file_worker/annivfflat_index_file_worker.cppm
  src/storage/buffer/file_worker/data_file_worker.cppm
  src/storage/buffer/file_worker/file_worker.cppm
  src/storage/buffer/file_worker/file_worker_type.cppm
  src/storage/buffer/file_worker/hnsw_file_worker.cppm
  src/storage/buffer/file_worker/index_file_worker.cppm
  src/storage/buffer/file_worker/raw_file_worker.cppm
  src/storage/buffer/file_worker/secondary_index_file_worker.cppm
  src/storage/buffer/file_worker/version_file_worker.cppm
Labels: ci

#1301 Added weighted_sum fusion
  src/common/stl.cppm
  src/executor/operator/physical_fusion.cpp
  src/executor/operator/physical_fusion.cppm
  src/executor/operator/physical_scan/physical_knn_scan.cppm
  src/executor/operator/physical_scan/physical_merge_knn.cppm
  src/expression/knn_expression.cppm
  test/sql/dql/fusion.slt
Labels: ci

#1302 Changed weighted_sum normalization method
  src/executor/operator/physical_fusion.cpp
  test/sql/dql/fusion.slt
Labels: ci

#1303 Escape reserved character in query string
  python/hello_infinity.py
  src/parser/expression_lexer.cpp
  src/parser/expression_lexer.h
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/location.hh
  src/parser/search_lexer.cpp
  src/parser/search_lexer.h
  src/parser/search_lexer.l
  src/parser/search_parser.cpp
  src/parser/search_parser.h
  src/parser/search_parser.y
  src/storage/invertedindex/search/search_driver.cpp
  src/storage/invertedindex/search/search_driver.h
  src/unit_test/parser/search_driver.cpp
  test/sql/dql/fulltext/fulltext.slt
Labels: ci

#1304 Fix: mem leak.
  src/parser/type/info/sparse_info.cpp
  src/parser/type/info/sparse_info.h
Labels: ci

#1305 Add EMVB search: Part 1
  .github/workflows/tests.yml
  src/common/stl.cppm
  src/storage/knn_index/emvb/emvb_result_handler.cppm
  src/storage/knn_index/emvb/emvb_search.cpp
  src/storage/knn_index/emvb/emvb_search.cppm
  src/storage/knn_index/emvb/emvb_simd_funcs.cppm
  src/storage/knn_index/mlas_matrix_multiply.cpp
  src/storage/knn_index/mlas_matrix_multiply.cppm
  src/unit_test/storage/knnindex/emvb_search/test_emvb.cpp
  src/unit_test/storage/knnindex/emvb_search/test_simd.cpp
Labels: ci

#1307 Secondary index support string
  src/parser/type/data_type.h
  src/planner/optimizer/secondary_index_scan/secondary_index_scan_execute_expression.cpp
  src/planner/optimizer/secondary_index_scan/secondary_index_scan_execute_expression.cppm
  src/storage/meta/iter/block_column_iter.cppm
  src/storage/secondary_index/secondary_index_data.cpp
  src/storage/secondary_index/secondary_index_data.cppm
  src/storage/secondary_index/secondary_index_in_mem.cpp
  test/sql/dql/index_scan/index_scan_str.slt
Labels: ci

#1309 Introduced CutGrain for Chinese analyzer
  python/hello_infinity.py
  src/common/analyzer/analyzer.cppm
  src/common/analyzer/analyzer_pool.cpp
  src/common/analyzer/chinese_analyzer.cppm
  src/unit_test/common/analyzer/chinese_analyzer.cpp
  src/unit_test/parser/search_driver.cpp
Labels: ci

#1310 Improve Chinese analyzer
  src/common/analyzer/analyzer.cppm
  src/common/analyzer/chinese_analyzer.cpp
  src/common/analyzer/chinese_analyzer.cppm
  src/common/analyzer/common_analyzer.cpp
  src/common/analyzer/common_analyzer.cppm
  src/common/analyzer/japanese_analyzer.cpp
  third_party/cppjieba/.gitignore
  third_party/cppjieba/CMakeLists.txt
  third_party/cppjieba/ChangeLog.md
  third_party/cppjieba/deps/limonp/.github/workflows/cmake.yml
  third_party/cppjieba/deps/limonp/.gitignore
  third_party/cppjieba/deps/limonp/.travis.yml
  third_party/cppjieba/deps/limonp/CMakeLists.txt
  third_party/cppjieba/deps/limonp/ChangeLog.md
  third_party/cppjieba/deps/limonp/include/limonp/ArgvContext.hpp
  third_party/cppjieba/deps/limonp/include/limonp/BlockingQueue.hpp
  third_party/cppjieba/deps/limonp/include/limonp/BoundedBlockingQueue.hpp
  third_party/cppjieba/deps/limonp/include/limonp/BoundedQueue.hpp
  third_party/cppjieba/deps/limonp/include/limonp/Closure.hpp
  third_party/cppjieba/deps/limonp/include/limonp/Colors.hpp
  third_party/cppjieba/deps/limonp/include/limonp/Condition.hpp
  third_party/cppjieba/deps/limonp/include/limonp/Config.hpp
  third_party/cppjieba/deps/limonp/include/limonp/FileLock.hpp
  third_party/cppjieba/deps/limonp/include/limonp/ForcePublic.hpp
  third_party/cppjieba/deps/limonp/include/limonp/Md5.hpp
  third_party/cppjieba/deps/limonp/include/limonp/MutexLock.hpp
  third_party/cppjieba/deps/limonp/include/limonp/NonCopyable.hpp
  third_party/cppjieba/deps/limonp/include/limonp/Thread.hpp
  third_party/cppjieba/deps/limonp/include/limonp/ThreadPool.hpp
  third_party/cppjieba/include/cppjieba/Jieba.hpp
Labels: ci

#1311 Sparse hnsw
  benchmark/local_infinity/sparse/sparse_benchmark.cpp
  src/storage/knn_index/knn_hnsw/data_store/data_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/graph_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/lvq_vec_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/plain_vec_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/sparse_vec_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/vec_store_type.cppm
  src/storage/knn_index/knn_hnsw/dist_func_sparse_ip.cppm
  src/storage/knn_index/knn_hnsw/hnsw_alg.cppm
  src/storage/knn_index/knn_hnsw/hnsw_common.cppm
  src/storage/knn_index/sparse/linscan_alg.cpp
  src/storage/knn_index/sparse/linscan_alg.cppm
  src/storage/knn_index/sparse/sparse_test_util.cppm
  src/storage/knn_index/sparse/sparse_util.cpp
  src/storage/knn_index/sparse/sparse_util.cppm
  src/unit_test/storage/knnindex/knn_hnsw/test_dist_func2.cpp
  src/unit_test/storage/knnindex/knn_hnsw/test_hnsw.cpp
  src/unit_test/storage/knnindex/knn_hnsw/test_hnsw_bitmask.cpp
  src/unit_test/storage/knnindex/knn_hnsw/test_hnsw_sparse.cpp
  src/unit_test/storage/knnindex/knn_hnsw/test_lvq.cpp
  src/unit_test/storage/knnindex/knn_sparse/test_linscan.cpp
Labels: ci

#1313 Fix a bug of Chinese phrase query
  scripts/Dockerfile_infinity_builder_ubuntu2310
  src/common/analyzer/chinese_analyzer.cppm
  src/storage/invertedindex/in_doc_pos_iterator.cpp
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_phrase_doc_iterator.cpp
  src/storage/invertedindex/search/search_driver.cpp
  src/unit_test/common/analyzer/chinese_analyzer.cpp
  src/unit_test/storage/invertedindex/column_inverter.cpp
  src/unit_test/storage/invertedindex/memory_indexer.cpp
Labels: ci

#1314 Update stemmer
  src/common/analyzer/stemmer/api.h
  src/common/analyzer/stemmer/header.h
  src/common/analyzer/stemmer/stem_UTF_8_danish.cpp
  src/common/analyzer/stemmer/stem_UTF_8_danish.h
  src/common/analyzer/stemmer/stem_UTF_8_dutch.cpp
  src/common/analyzer/stemmer/stem_UTF_8_dutch.h
  src/common/analyzer/stemmer/stem_UTF_8_english.cpp
  src/common/analyzer/stemmer/stem_UTF_8_english.h
  src/common/analyzer/stemmer/stem_UTF_8_finnish.cpp
  src/common/analyzer/stemmer/stem_UTF_8_finnish.h
  src/common/analyzer/stemmer/stem_UTF_8_french.cpp
  src/common/analyzer/stemmer/stem_UTF_8_french.h
  src/common/analyzer/stemmer/stem_UTF_8_german.cpp
  src/common/analyzer/stemmer/stem_UTF_8_german.h
  src/common/analyzer/stemmer/stem_UTF_8_hungarian.cpp
  src/common/analyzer/stemmer/stem_UTF_8_hungarian.h
  src/common/analyzer/stemmer/stem_UTF_8_italian.cpp
  src/common/analyzer/stemmer/stem_UTF_8_italian.h
  src/common/analyzer/stemmer/stem_UTF_8_norwegian.cpp
  src/common/analyzer/stemmer/stem_UTF_8_norwegian.h
  src/common/analyzer/stemmer/stem_UTF_8_porter.cpp
  src/common/analyzer/stemmer/stem_UTF_8_porter.h
  src/common/analyzer/stemmer/stem_UTF_8_portuguese.cpp
  src/common/analyzer/stemmer/stem_UTF_8_portuguese.h
  src/common/analyzer/stemmer/stem_UTF_8_romanian.cpp
  src/common/analyzer/stemmer/stem_UTF_8_romanian.h
  src/common/analyzer/stemmer/stem_UTF_8_russian.cpp
  src/common/analyzer/stemmer/stem_UTF_8_russian.h
  src/common/analyzer/stemmer/stem_UTF_8_spanish.cpp
  src/common/analyzer/stemmer/stem_UTF_8_spanish.h
  src/common/analyzer/stemmer/stem_UTF_8_swedish.h
  src/common/analyzer/stemmer/stem_UTF_8_turkish.cpp
  src/common/analyzer/stemmer/stem_UTF_8_turkish.h
  src/common/analyzer/stemmer/stemmer.cpp
  src/common/analyzer/stemmer/stemmer.cppm
Labels: ci

#1315 Add EMVB search: Part 2
  src/CMakeLists.txt
  src/common/stl.cppm
  src/storage/knn_index/emvb/emvb_search.cpp
  src/storage/knn_index/emvb/emvb_search.cppm
  src/storage/knn_index/emvb/product_quantizer.cpp
  src/storage/knn_index/emvb/product_quantizer.cppm
  src/storage/knn_index/mlas_matrix_multiply.cpp
  src/storage/knn_index/mlas_matrix_multiply.cppm
  src/unit_test/storage/knnindex/emvb_search/test_emvb.cpp
  third_party/CControl/CControl_svd.h
  third_party/CControl/LICENSE
  third_party/CControl/NOTICE
  third_party/CControl/README.md
  third_party/versions
Labels: ci, wip

#1316 Fix: wal read/write bug
  src/parser/type/data_type.cpp
Labels: ci

#1318 Add EMVB search: Part 3
  src/storage/knn_index/emvb/emvb_index.cpp
  src/storage/knn_index/emvb/emvb_index.cppm
  src/storage/knn_index/emvb/emvb_search.cpp
  src/storage/knn_index/emvb/emvb_search.cppm
  src/storage/knn_index/emvb/emvb_shared_vec.cpp
  src/storage/knn_index/emvb/emvb_shared_vec.cppm
  src/storage/knn_index/emvb/product_quantizer.cpp
  src/storage/knn_index/emvb/product_quantizer.cppm
  src/unit_test/storage/knnindex/emvb_search/test_emvb.cpp
  third_party/CControl/CControl_svd.h
Labels: ci

#1321 Supporting export one embedding column to FVECS file
  src/executor/operator/physical_export.cpp
  src/executor/operator/physical_export.cppm
  src/executor/operator/physical_import.cpp
  src/executor/physical_planner.cpp
  src/parser/expression_lexer.cpp
  src/parser/expression_lexer.h
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/search_lexer.cpp
  src/parser/search_lexer.h
  src/parser/statement/copy_statement.cpp
  src/parser/statement/copy_statement.h
  src/parser/table_reference/base_table_reference.cpp
  src/planner/logical_planner.cpp
  src/planner/node/logical_export.cppm
Labels: ci

#1324 Fix: bug of import without flush version.
  python/README.md
  src/storage/knn_index/knn_hnsw/data_store/data_store.cppm
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/meta/entry/segment_entry.cpp
  src/storage/meta/entry/segment_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
  src/storage/txn/txn.cpp
  src/storage/txn/txn_store.cpp
Labels: ci

#1329 Add quickwit client to benchmark
  docs/references/benchmark.md
  python/benchmark/clients/quickwit_client.py
  python/benchmark/configs/elasticsearch_tantivy.json
  python/benchmark/configs/infinity_tantivy.json
  python/benchmark/configs/quickwit_enwiki.json
  python/benchmark/configs/quickwit_enwiki_index.yaml
  python/benchmark/configs/quickwit_tantivy.json
  python/benchmark/configs/quickwit_tantivy_index.yaml
  python/benchmark/run.py
Labels: ci

#1328 Supports importing BVECS file.
  .gitignore
  python/infinity/remote_thrift/client.py
  python/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/pyproject.toml
  python/test/test_index.py
  python/test_http_api/test_index.py
  src/executor/explain_physical_plan.cpp
  src/executor/operator/physical_import.cpp
  src/executor/operator/physical_import.cppm
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/statement/copy_statement.cpp
  src/parser/statement/statement_common.h
  src/planner/explain_ast.cpp
  src/planner/explain_logical_plan.cpp
  src/planner/node/logical_export.cpp
  src/planner/node/logical_import.cpp
  test/sql/ddl/type/test_sparse_default.slt
  test/sql/dml/import/test_import_sparse_csv.slt
  test/sql/dml/import/test_import_sparse_jsonl.slt
  test/sql/dml/insert/test_insert_sparse.slt
  test/sql/dql/knn/sparse/test_knn_sparse.slt
  test/sql/dql/knn/sparse/test_knn_sparse_bit.slt
  test/sql/dql/knn/sparse/test_knn_sparse_integer.slt
  test/sql/dql/sort_top/sort_by_function.slt
  thrift/infinity.thrift
  tools/generate_big_sparse.py
  tools/generate_bvecs.py
  tools/generate_csr.py
  tools/sqllogictest.py
Labels: ci

#1334 Fix filter expression can't include row_id
  python/infinity/remote_thrift/utils.py
Labels: ci

#1335 Fix: abort early in column info check if ColumnExpression is special expression
  src/planner/optimizer/secondary_index_scan/filter_expression_push_down.cpp
Labels: ci

#1333 Feature: export select columns
  src/common/status.cpp
  src/common/status.cppm
  src/executor/operator/physical_export.cpp
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/statement/copy_statement.cpp
  src/parser/statement/copy_statement.h
  src/planner/logical_planner.cpp
Labels: ci

#1336 Update EXPORT interface of python and HTTP
  python/infinity/errors.py
  python/infinity/remote_thrift/client.py
  python/infinity/remote_thrift/db.py
  python/infinity/remote_thrift/infinity.py
  python/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/infinity/remote_thrift/query_builder.py
  python/infinity/remote_thrift/table.py
  python/infinity/remote_thrift/utils.py
  python/infinity/table.py
  python/pyproject.toml
  python/test/test_basic.py
  python/test/test_table.py
  python/test/test_update.py
  src/executor/operator/physical_export.cpp
  src/function/builtin_functions.cpp
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/network/http_server.cpp
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  test/sql/dql/select_ts.slt
  thrift/infinity.thrift
Labels: ci

#1338 Fix sparse expression parsing memory leak
  CMakeLists.txt
  benchmark/polling_scheduler/CMakeLists.txt
  benchmark/polling_scheduler/buffer.h
  benchmark/polling_scheduler/buffer_queue.h
  benchmark/polling_scheduler/fragment.cpp
  benchmark/polling_scheduler/fragment.h
  benchmark/polling_scheduler/operator.h
  benchmark/polling_scheduler/poller_queue.h
  benchmark/polling_scheduler/scheduler_benchmark.cpp
  benchmark/polling_scheduler/task.cpp
  benchmark/polling_scheduler/task.h
  benchmark/polling_scheduler/task_queue.h
  src/parser/expr/match_sparse_expr.cpp
  test/sql/dql/knn/sparse/test_knn_sparse_integer.slt
Labels: ci

#1331 Add EMVB search: Part 4
  src/executor/operator/physical_show.cpp
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/statement/extra/create_index_info.cpp
  src/parser/statement/extra/create_index_info.h
  src/planner/logical_planner.cpp
  src/storage/buffer/file_worker/emvb_index_file_worker.cpp
  src/storage/buffer/file_worker/emvb_index_file_worker.cppm
  src/storage/buffer/file_worker/file_worker_type.cppm
  src/storage/buffer/file_worker/index_file_worker.cppm
  src/storage/definition/index_base.cpp
  src/storage/definition/index_emvb.cpp
  src/storage/definition/index_emvb.cppm
  src/storage/knn_index/emvb/emvb_index.cpp
  src/storage/knn_index/emvb/emvb_index.cppm
  src/storage/knn_index/emvb/emvb_index_in_mem.cpp
  src/storage/knn_index/emvb/emvb_index_in_mem.cppm
  src/storage/knn_index/emvb/emvb_shared_vec.cppm
  src/storage/knn_index/emvb/product_quantizer.cpp
  src/storage/knn_index/emvb/product_quantizer.cppm
  src/storage/meta/entry/chunk_index_entry.cpp
  src/storage/meta/entry/chunk_index_entry.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/unit_test/storage/knnindex/emvb_search/test_emvb.cpp
  tools/generate_emvb_test_data.py
  tools/sqllogictest.py
Labels: ci

#1339 Fix data race during WAL replay
  src/main/config.cpp
  src/storage/meta/catalog.cpp
  src/storage/meta/catalog.cppm
  src/storage/storage.cpp
  src/storage/wal/wal_manager.cpp
Labels: ci

#1341 Fix data race of pg server and hnsw
  scripts/stop_infinity.sh
  src/bin/infinity_main.cpp
  src/network/pg_server.cpp
  src/network/pg_server.cppm
  src/storage/knn_index/knn_hnsw/hnsw_alg.cppm
Labels: ci

#1342 Fix bmw busy loop
  docs/references/benchmark.md
  python/benchmark/clients/quickwit_client.py
  src/common/third_party.cppm
  src/executor/operator/physical_match.cpp
  src/main/session.cppm
  src/network/buffer_reader.cpp
  src/network/connection.cppm
  src/network/pg_server.cpp
  src/storage/invertedindex/multi_posting_decoder.cpp
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_phrase_doc_iterator.cpp
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_term_doc_iterator.cpp
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_wand_iterator.cpp
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_wand_iterator.cppm
  src/storage/invertedindex/search/early_terminate_iterator/early_terminate_iterator.cpp
  src/storage/invertedindex/search/early_terminate_iterator/early_terminate_iterator.cppm
Labels: ci

#1347 Show active transaction
  CMakeLists.txt
  python/README.md
  python/test/infinity/test_knn.py
  src/common/status.cpp
  src/common/status.cppm
  src/executor/explain_physical_plan.cpp
  src/executor/operator/physical_show.cpp
  src/executor/operator/physical_show.cppm
  src/executor/physical_planner.cpp
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/lexer.l
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser.y
  src/parser/statement/show_statement.cpp
  src/parser/statement/show_statement.h
  src/planner/explain_ast.cpp
  src/planner/explain_logical_plan.cpp
  src/planner/logical_planner.cpp
  src/planner/logical_planner.cppm
  src/planner/node/logical_show.cpp
  src/planner/node/logical_show.cppm
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
Labels: ci

#1348 Add EMVB search: Part 5
  src/CMakeLists.txt
  src/executor/operator/physical_scan/physical_match_tensor_scan.cpp
  src/executor/operator/physical_scan/physical_match_tensor_scan.cppm
  src/executor/operator_state.cppm
  src/executor/physical_planner.cpp
  src/function/table/match_tensor_scan_data.cppm
  src/scheduler/fragment_context.cpp
  src/storage/common/block_index.cpp
  src/storage/knn_index/emvb/eigen_svd.cpp
  src/storage/knn_index/emvb/eigen_svd.cppm
  src/storage/knn_index/emvb/emvb_index.cpp
  src/storage/knn_index/emvb/emvb_index.cppm
  src/storage/knn_index/emvb/emvb_index_in_mem.cpp
  src/storage/knn_index/emvb/emvb_index_in_mem.cppm
  src/storage/knn_index/emvb/emvb_result_handler.cppm
  src/storage/knn_index/emvb/emvb_search.cpp
  src/storage/knn_index/emvb/emvb_search.cppm
  src/storage/knn_index/emvb/product_quantizer.cpp
  third_party/CControl/CControl_svd.h
  third_party/CControl/LICENSE
  third_party/CControl/NOTICE
  third_party/CControl/README.md
  third_party/eigen-3.4.0/COPYING.MPL2
  third_party/eigen-3.4.0/COPYING.README
  third_party/eigen-3.4.0/JacobiSVD.h
  third_party/eigen-3.4.0/NOTICE
  third_party/eigen-3.4.0/README.md
  third_party/versions
  tools/generate_emvb_test_data_2.py
  tools/sqllogictest.py
Labels: ci

#1349 fix local infinity test failed
  .github/workflows/tests.yml
  pyproject.toml
  python/README.md
  python/hello_infinity.py
  python/infinity/index.py
  python/infinity/local_infinity/client.py
  python/infinity/local_infinity/db.py
  python/infinity/local_infinity/infinity.py
  python/infinity/local_infinity/query_builder.py
  python/infinity/local_infinity/table.py
  python/infinity/local_infinity/types.py
  python/infinity/local_infinity/utils.py
  python/infinity/table.py
  python/test/infinity/test_knn.py
  python/test/test_basic.py
  src/CMakeLists.txt
  src/unit_test/storage/invertedindex/search/query_match.cpp
  test/sql/dql/fulltext/fulltext.slt
  tools/run_pysdk_local_infinity_test.py
Labels: ci

#1354 Add python script for flat knn scan benchmark
  python/benchmark/flat_knn/flat_knn_interactive_benchmark.py
  python/benchmark/legacy_benchmark/remote_benchmark_knn.py
  src/storage/buffer/file_worker/data_file_worker.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_index_entry.cpp
  src/unit_test/storage/bg_task/compact_segments_task.cpp
  src/unit_test/storage/column_vector/column_vector_bool.cpp
  src/unit_test/storage/column_vector/column_vector_date_time.cpp
  src/unit_test/storage/column_vector/column_vector_decimal.cpp
  src/unit_test/storage/column_vector/column_vector_embedding.cpp
  src/unit_test/storage/column_vector/column_vector_float.cpp
  src/unit_test/storage/column_vector/column_vector_geo.cpp
  src/unit_test/storage/column_vector/column_vector_integer.cpp
  src/unit_test/storage/column_vector/column_vector_row.cpp
  src/unit_test/storage/column_vector/column_vector_uuid.cpp
  src/unit_test/storage/column_vector/column_vector_varchar.cpp
  test/data/config/test_cleanup_task_silent.toml
  tools/sqllogictest.py
Labels: ci

#1353 Fix several bugs
  python/hello_embedding.py
  python/infinity/__init__.py
  python/test.py
  python/test/infinity/test_basic.py
  python/test/infinity/test_database.py
  python/test/infinity/test_delete.py
  python/test/infinity/test_insert.py
  python/test/infinity/test_knn.py
  python/test/infinity/test_select.py
  python/test/infinity/test_table.py
  python/test/infinity/test_update.py
  python/test/src/test_basic.py
  python/test/src/test_database.py
  python/test/src/test_delete.py
  python/test/src/test_insert.py
  python/test/src/test_knn.py
  python/test/src/test_py_import.py
  python/test/src/test_select.py
  python/test/src/test_table.py
  python/test/src/test_update.py
  python/test_http_api/httpapibase.py
  python/test_http_api/test_import.py
  python/test_http_api/test_index.py
  src/common/status.cpp
  src/common/status.cppm
  src/embedded_infinity/wrap_infinity.cpp
  src/executor/operator/physical_show.cpp
  src/main/infinity.cpp
  src/network/http_server.cpp
  src/network/infinity_thrift_service.cpp
  src/storage/background_process.cpp
  src/storage/background_process.cppm
  src/storage/bg_task/bg_task.cppm
  src/storage/meta/entry/db_entry.cpp
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn_store.cpp
  src/storage/txn/txn_store.cppm
  src/storage/wal/wal_manager.cpp
  tools/bvecs_file_printer.py
  tools/run_http_api.py
Labels: ci

#1358 Fix bug in Merger Operators.
  src/executor/operator/physical_scan/physical_merge_knn.cpp
  src/executor/operator/physical_scan/physical_merge_match_sparse.cpp
Labels: ci

#1359 Fix scheduler
  src/scheduler/task_scheduler.cpp
Labels: ci

#1360 Fix several bugs
  python/infinity/__init__.py
  python/test/infinity/test_basic.py
  python/test/infinity/test_database.py
  python/test/infinity/test_delete.py
  python/test/infinity/test_insert.py
  python/test/infinity/test_knn.py
  python/test/infinity/test_select.py
  python/test/infinity/test_table.py
  python/test/infinity/test_update.py
  python/test/src/test_basic.py
  python/test/src/test_database.py
  python/test/src/test_delete.py
  python/test/src/test_insert.py
  python/test/src/test_knn.py
  python/test/src/test_py_import.py
  python/test/src/test_select.py
  python/test/src/test_table.py
  python/test/src/test_update.py
  python/test_http_api/httpapibase.py
  python/test_http_api/test_import.py
  python/test_http_api/test_index.py
  src/common/status.cpp
  src/common/status.cppm
  src/embedded_infinity/wrap_infinity.cpp
  src/executor/operator/physical_show.cpp
  src/main/infinity.cpp
  src/network/http_server.cpp
  src/network/infinity_thrift_service.cpp
  src/storage/background_process.cpp
  src/storage/background_process.cppm
  src/storage/bg_task/bg_task.cppm
  src/storage/meta/entry/db_entry.cpp
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn_store.cpp
  src/storage/txn/txn_store.cppm
  src/storage/wal/wal_manager.cpp
  tools/run_http_api.py
Labels: ci

#1363 Fix analyzer issues
  src/common/analyzer/standard_analyzer.cppm
  third_party/cppjieba/include/cppjieba/PreFilter.hpp
Labels: ci

#1362 Fix phrase bug
  docs/getstarted/build_from_source.md
  docs/getstarted/quickstart.md
  docs/references/pysdk_api_reference.md
  python/hello_infinity.py
  src/storage/invertedindex/format/position_list_encoder.cpp
  src/storage/invertedindex/format/skiplist_reader.cppm
  src/storage/invertedindex/posting_iterator.cpp
  src/storage/invertedindex/posting_iterator.cppm
  src/storage/invertedindex/search/phrase_doc_iterator.cpp
  src/storage/invertedindex/search/search_driver.cpp
  src/unit_test/common/analyzer/chinese_analyzer.cpp
  src/unit_test/common/analyzer/standard_analyzer.cpp
  src/unit_test/storage/invertedindex/memory_indexer.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
Labels: ci

#1364 Add default topn for vector and sparse
  python/infinity/common.py
  python/infinity/local_infinity/query_builder.py
  python/infinity/local_infinity/table.py
  python/infinity/remote_thrift/query_builder.py
  python/infinity/remote_thrift/table.py
  src/common/default_values.cppm
  src/executor/operator/physical_fusion.cpp
  src/executor/physical_planner.cpp
  src/parser/expr/knn_expr.h
  src/parser/expr/match_sparse_expr.h
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/lexer.l
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser.y
  src/parser/statement/statement_common.h
  src/planner/bound_select_statement.cpp
  src/storage/wal/wal_manager.cpp
Labels: ci

#1368 Provide search option for tensor
  src/common/default_values.cppm
  src/executor/operator/physical_scan/physical_match_tensor_scan.cpp
  src/executor/operator/physical_scan/physical_match_tensor_scan.cppm
  src/executor/physical_planner.cpp
  src/planner/node/logical_match_scan/logical_match_tensor_scan.cpp
  src/planner/node/logical_match_scan/logical_match_tensor_scan.cppm
Labels: ci

#1367 Update flat knn scan scheduler
  python/benchmark/legacy_benchmark/remote_benchmark_knn.py
  src/executor/operator/physical_scan/physical_knn_scan.cpp
  src/executor/operator/physical_scan/physical_knn_scan.cppm
  src/function/table/knn_scan_data.cpp
  src/function/table/knn_scan_data.cppm
  src/scheduler/fragment_context.cpp
  src/scheduler/task_scheduler.cpp
  src/storage/knn_index/ann_ivf/some_simd_functions.cpp
  src/storage/knn_index/ann_ivf/some_simd_functions.cppm
  test/sql/explain/explain_fusion.slt
Labels: ci

#1370 Replace the fine grained Chinese analyzer with a new one
  src/common/analyzer/chinese_analyzer.cpp
  third_party/cppjieba/include/cppjieba/QuerySegment.hpp
Labels: ci

#1371 Update doc for tensor search
  docs/references/pysdk_api_reference.md
  src/storage/knn_index/emvb/emvb_search.cpp
  tools/generate_emvb_test_data.py
  tools/sqllogictest.py
Labels: ci

#1361 Bmp idx 3
  .gitignore
  benchmark/local_infinity/sparse/bmp_benchmark.cpp
  benchmark/local_infinity/sparse/sparse_benchmark_util.h
  src/executor/operator/physical_optimize.cpp
  src/executor/operator/physical_optimize.cppm
  src/executor/operator/physical_scan/physical_match_sparse_scan.cpp
  src/executor/operator/physical_scan/physical_match_sparse_scan.cppm
  src/executor/operator_state.cppm
  src/executor/physical_planner.cpp
  src/function/table/match_sparse_scan_data.cppm
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/statement/optimize_statement.h
  src/planner/logical_planner.cpp
  src/planner/node/logical_optimize.cppm
  src/scheduler/fragment_context.cpp
  src/storage/buffer/file_worker/bmp_index_file_worker.cpp
  src/storage/common/block_index.cpp
  src/storage/common/block_index.cppm
  src/storage/knn_index/sparse/bmp_alg.cpp
  src/storage/knn_index/sparse/bmp_alg.cppm
  src/storage/knn_index/sparse/bmp_alg_serialize.cpp
  src/storage/knn_index/sparse/bmp_posting.cpp
  src/storage/knn_index/sparse/bmp_util.cpp
  src/storage/knn_index/sparse/bmp_util.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cppm
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/meta/entry/table_index_entry.cppm
  src/unit_test/storage/knnindex/knn_sparse/test_bmp_index.cpp
  test/sql/dql/knn/sparse/test_knn_sparse_bmp.slt
  test/sql/dql/knn/sparse/test_knn_sparse_bmp_filter.slt
  test/sql/dql/knn/sparse/test_knn_sparse_bmp_realtime.slt
Labels: ci

#1372 Copy resource into rpm, deb and image
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  scripts/Dockerfile_infinity
Labels: ci

#1378 Support traditional Chinese for full text search
  benchmark/local_infinity/CMakeLists.txt
  benchmark/remote_infinity/CMakeLists.txt
  src/CMakeLists.txt
  src/common/analyzer/analyzer_pool.cpp
  src/common/analyzer/analyzer_pool.cppm
  src/common/analyzer/chinese_analyzer.cppm
  src/common/analyzer/traditional_chinese_analyzer.cpp
  src/common/analyzer/traditional_chinese_analyzer.cppm
  third_party/CMakeLists.txt
  third_party/opencc/CMakeLists.txt
  third_party/opencc/config_reader.c
  third_party/opencc/config_reader.h
  third_party/opencc/converter.c
  third_party/opencc/converter.h
  third_party/opencc/dictionary/abstract.c
  third_party/opencc/dictionary/abstract.h
  third_party/opencc/dictionary/datrie.c
  third_party/opencc/dictionary/datrie.h
  third_party/opencc/dictionary/text.c
  third_party/opencc/dictionary/text.h
  third_party/opencc/dictionary_group.c
  third_party/opencc/dictionary_group.h
  third_party/opencc/dictionary_set.c
  third_party/opencc/dictionary_set.h
  third_party/opencc/encoding.c
  third_party/opencc/encoding.h
  third_party/opencc/opencc.c
  third_party/opencc/opencc.h
  third_party/opencc/opencc_types.h
  third_party/opencc/openccxx.cpp
  third_party/opencc/openccxx.h
  third_party/opencc/utils.c
  third_party/opencc/utils.h
Labels: ci

#1381 Add script for generating data for benchmark
  .github/workflows/tests.yml
  python/benchmark/mldr_benchmark/LICENSE
  python/benchmark/mldr_benchmark/NOTICE
  python/benchmark/mldr_benchmark/generate_colbert_embedding.py
  python/benchmark/mldr_benchmark/generate_dense_embedding.py
  python/benchmark/mldr_benchmark/generate_sparse_embedding.py
  python/benchmark/mldr_benchmark/sparse_json_data_transform.py
  python/infinity/index.py
  python/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/test/infinity/test_index.py
  python/test/src/test_index.py
  src/embedded_infinity_ext.cpp
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/parser/parser.cpp
  src/parser/parser.y
  thrift/infinity.thrift
Labels: ci

#1379 Support relative path for data and wal files.
  python/test/src/test_index.py
  src/common/utility/random.cpp
  src/common/utility/random.cppm
  src/storage/invertedindex/column_index_reader.cpp
  src/storage/meta/catalog.cpp
  src/storage/meta/catalog.cppm
  src/storage/meta/db_meta.cpp
  src/storage/meta/db_meta.cppm
  src/storage/meta/entry/base_entry.cppm
  src/storage/meta/entry/block_column_entry.cpp
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/meta/entry/chunk_index_entry.cpp
  src/storage/meta/entry/db_entry.cpp
  src/storage/meta/entry/db_entry.cppm
  src/storage/meta/entry/segment_entry.cpp
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/meta/entry/table_index_entry.cppm
  src/storage/meta/table_index_meta.cpp
  src/storage/meta/table_meta.cpp
  src/storage/meta/table_meta.cppm
  src/storage/storage.cpp
  src/storage/storage.cppm
  src/storage/txn/txn.cpp
  src/storage/wal/log_file.cpp
  src/storage/wal/log_file.cppm
  src/storage/wal/wal_entry.cpp
  src/storage/wal/wal_entry.cppm
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
  src/unit_test/storage/wal/wal_entry.cpp
Labels: ci

#1382 Sloppy phrase
  docs/references/pysdk_api_reference.md
  example/fulltext_search.py
  python/hello_infinity.py
  src/parser/expression_lexer.cpp
  src/parser/expression_lexer.h
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/search_lexer.cpp
  src/parser/search_lexer.h
  src/parser/search_lexer.l
  src/parser/search_parser.cpp
  src/parser/search_parser.h
  src/parser/search_parser.y
  src/storage/invertedindex/search/bm25_ranker.cpp
  src/storage/invertedindex/search/bm25_ranker.cppm
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_phrase_doc_iterator.cpp
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_phrase_doc_iterator.cppm
  src/storage/invertedindex/search/match_data.cppm
  src/storage/invertedindex/search/phrase_doc_iterator.cpp
  src/storage/invertedindex/search/phrase_doc_iterator.cppm
  src/storage/invertedindex/search/query_node.cpp
  src/storage/invertedindex/search/search_driver.cpp
  src/storage/invertedindex/search/search_driver.h
  src/unit_test/base_test.h
  src/unit_test/parser/search_driver.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
Labels: ci

#1385 Sparse python api
  python/infinity/common.py
  python/infinity/index.py
  python/infinity/local_infinity/client.py
  python/infinity/local_infinity/db.py
  python/infinity/local_infinity/query_builder.py
  python/infinity/local_infinity/table.py
  python/infinity/local_infinity/types.py
  python/infinity/remote_thrift/client.py
  python/infinity/remote_thrift/db.py
  python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService-remote
  python/infinity/remote_thrift/infinity_thrift_rpc/InfinityService.py
  python/infinity/remote_thrift/infinity_thrift_rpc/constants.py
  python/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/infinity/remote_thrift/query_builder.py
  python/infinity/remote_thrift/table.py
  python/infinity/remote_thrift/types.py
  python/test/conftest.py
  python/test/infinity/test_index.py
  python/test/infinity/test_insert.py
  python/test/infinity/test_knn.py
  python/test/src/test_index.py
  python/test/src/test_insert.py
  python/test/src/test_knn.py
  src/embedded_infinity/wrap_infinity.cpp
  src/embedded_infinity/wrap_infinity.cppm
  src/embedded_infinity_ext.cpp
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/main/query_options.cppm
  src/network/infinity_thrift/InfinityService.cpp
  src/network/infinity_thrift/InfinityService.h
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  src/network/infinity_thrift_types.cppm
  src/parser/expr/match_sparse_expr.cpp
  src/parser/expr/match_sparse_expr.h
  src/parser/type/data_type.cpp
  src/parser/type/info/sparse_info.cpp
  src/parser/type/info/sparse_info.h
  thrift/infinity.thrift
Labels: ci

#1383 Update pysdk version to 0.2.0.dev8 for test
  example/delete_update_data.py
  example/fulltext_search.py
  example/fulltext_search_zh.py
  example/fusion_search.py
  example/import_data.py
  example/simple_example.py
  example/vector_search.py
  pyproject.toml
  python/hello_infinity.py
  python/hello_infinity_cn.py
  python/infinity/remote_thrift/client.py
  src/executor/operator/physical_update.cpp
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  src/network/thrift_server.cpp
Labels: ci

#1386 Update sparse vector doc
  docs/references/pysdk_api_reference.md
  python/test/infinity/test_knn.py
Labels: documentation

#1390 Fix build script for nanobind
  CMakeLists.txt
  pyproject.toml
  src/CMakeLists.txt
Labels: ci

#1391 Fix float export
  python/test/src/test_basic.py
  src/parser/type/complex/embedding_type.h
  src/storage/column_vector/value.cpp
  tools/generate_big_sparse.py
  tools/generate_csr.py
  tools/generate_util/format_data.py
Labels: ci

#1392 Fix: use static link for nanobind
  src/CMakeLists.txt
Labels: ci

#1395 Rerank hnsw lvq
  .github/workflows/tests.yml
  CMakeLists.txt
  benchmark/local_infinity/knn/knn_query_benchmark.cpp
  src/common/utility/exception.cpp
  src/common/utility/exception.cppm
  src/executor/operator/physical_match.cpp
  src/executor/operator/physical_scan/physical_knn_scan.cpp
  src/executor/operator/physical_scan/physical_knn_scan.cppm
  src/storage/buffer/buffer_manager.cpp
  src/storage/buffer/buffer_manager.cppm
  src/storage/buffer/buffer_obj.cpp
  src/storage/buffer/buffer_obj.cppm
  src/storage/column_vector/column_vector.cppm
  src/storage/knn_index/knn_hnsw/abstract_hnsw.cppm
  src/storage/knn_index/merge_knn.cppm
  src/unit_test/main/query_profiler.cpp
  src/unit_test/storage/buffer/buffer_manager.cpp
  src/unit_test/storage/buffer/buffer_obj.cpp
  src/unit_test/storage/wal/wal_replay.cpp
  test/sql/dql/knn/embedding/test_knn_hnsw_l2_lvq.slt
Labels: ci

#1398 Fix convert between embeddings
  example/delete_update_data.py
  src/expression/cast_expression.cpp
Labels: ci

#1399 Add export offset and limit
  src/executor/operator/physical_export.cpp
  src/executor/operator/physical_export.cppm
  src/executor/physical_planner.cpp
  src/parser/expression_lexer.cpp
  src/parser/expression_lexer.h
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/lexer.l
  src/parser/parser.cpp
  src/parser/parser.y
  src/parser/search_lexer.cpp
  src/parser/search_lexer.h
  src/parser/statement/copy_statement.h
  src/planner/logical_planner.cpp
  src/planner/node/logical_export.cpp
  src/planner/node/logical_export.cppm
  src/storage/column_vector/value.cpp
  test/sql/dml/export/test_export_default.slt
  test/sql/dml/export/test_export_embedding.slt
  test/sql/dml/import/test_export_embedding.slt
  tools/sqllogictest.py
Labels: ci

#1400 Opt bmp
  src/common/utility/exception.cpp
  src/common/utility/exception.cppm
  src/parser/type/serialize.cppm
  src/parser/type/serialize.h
  src/storage/knn_index/sparse/bmp_alg.cpp
  src/storage/knn_index/sparse/bmp_alg.cppm
  src/storage/knn_index/sparse/bmp_alg_serialize.cpp
  src/storage/knn_index/sparse/bmp_blockterms.cppm
  src/storage/knn_index/sparse/bmp_posting.cpp
  src/storage/knn_index/sparse/bmp_posting.cppm
  src/storage/knn_index/sparse/bmp_posting_serialize.cpp
Labels: ci

#1401 Add insert script for mldr benchmark
  python/benchmark/mldr_benchmark/generate_colbert_embedding.py
  python/benchmark/mldr_benchmark/generate_dense_embedding.py
  python/benchmark/mldr_benchmark/generate_sparse_embedding.py
  python/benchmark/mldr_benchmark/insert_data.py
  python/benchmark/mldr_benchmark/mldr_common_tools.py
  src/storage/column_vector/column_vector.cpp
Labels: ci

#1407 Optimize memory
  src/storage/invertedindex/common/external_sort_merger.cpp
  src/storage/invertedindex/memory_indexer.cpp
Labels: ci

#1406 Fix: data missing when flush block version file
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/meta/entry/block_version.cpp
  src/storage/meta/entry/segment_entry.cpp
Labels: ci

#1404 Install multiple python into builder image.
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  pyproject.toml
  python/README.md
  python/requirements.txt
  python/test/src/utils.py
  python/test_http_api/httputils.py
  scripts/Dockerfile_infinity_builder_centos7
  scripts/download_deps_infinity_builder_centos7.sh
  src/CMakeLists.txt
  tools/run_benchmark.py
  tools/run_http_api.py
  tools/run_parallel_test_continuous.py
  tools/run_pysdk_local_infinity_test.py
  tools/run_pysdk_remote_infinity_test.py
  tools/run_slow_test.py
Labels: ci

#1411 Removed resource from rpm, deb and image
  .github/workflows/release.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  scripts/Dockerfile_infinity
Labels: ci

#1412 Exact phrase optimization
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_phrase_doc_iterator.cpp
  src/storage/invertedindex/search/early_terminate_iterator/blockmax_phrase_doc_iterator.cppm
  src/storage/invertedindex/search/match_data.cppm
  src/storage/invertedindex/search/phrase_doc_iterator.cpp
  src/storage/invertedindex/search/phrase_doc_iterator.cppm
Labels: ci

#1413 Accelerate release CI process
  .github/workflows/tests.yml
  python/README.md
  tools/README.md
Labels: ci
