Repository infiniflow/infinity, pull requests merged in 2025-01, with the labels that each got.

#2416 Fix UnrecoverableError: Invalid MergeFlag: 1
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
  src/storage/txn/txn_store.cpp
  src/storage/txn/txn_store.cppm
Labels: ci

#2420 Fix show txn history without ongoing txn
  src/storage/io/s3_client_minio.cpp
  src/storage/txn/txn_manager.cpp
Labels: ci

#2419 Mmap3
  python/test_pysdk/test_knn.py
  src/parser/type/serialize.cppm
  src/parser/type/serialize.h
  src/storage/buffer/buffer_obj.cpp
  src/storage/buffer/file_worker/bmp_index_file_worker.cpp
  src/storage/buffer/file_worker/bmp_index_file_worker.cppm
  src/storage/buffer/file_worker/file_worker.cpp
  src/storage/buffer/file_worker/file_worker.cppm
  src/storage/io/virtual_store.cpp
  src/storage/io/virtual_store.cppm
  src/storage/knn_index/sparse/abstract_bmp.cpp
  src/storage/knn_index/sparse/abstract_bmp.cppm
  src/storage/knn_index/sparse/bmp_alg.cpp
  src/storage/knn_index/sparse/bmp_alg.cppm
  src/storage/knn_index/sparse/bmp_alg_serialize.cpp
  src/storage/knn_index/sparse/bmp_blockterms.cppm
  src/storage/knn_index/sparse/bmp_fwd.cppm
  src/storage/knn_index/sparse/bmp_ivt.cppm
  src/storage/knn_index/sparse/bmp_posting.cpp
  src/storage/knn_index/sparse/bmp_posting.cppm
  src/storage/knn_index/sparse/bmp_posting_serialize.cpp
  src/storage/knn_index/sparse/bmp_util.cppm
  src/storage/meta/entry/chunk_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/persistence/persistence_manager.cpp
  src/storage/persistence/persistence_manager.cppm
  src/unit_test/storage/knnindex/knn_sparse/test_bmp_fwd.cpp
  src/unit_test/storage/knnindex/knn_sparse/test_bmp_index.cpp
  src/unit_test/storage/knnindex/knn_sparse/test_bmp_ivt.cpp
  test/sql/dql/knn/sparse/test_knn_sparse_bmp.slt
  test/sql/dql/knn/sparse/test_knn_sparse_bmp_realtime.slt
  tools/generate_big_sparse.py
Labels: ci

#2421 Add snapshot, part2
  src/common/utility/utility.cppm
  src/executor/operator/physical_command.cpp
  src/executor/operator/snapshot/snapshot.cppm
  src/executor/operator/snapshot/table_snapshot.cpp
  src/parser/statement/command_statement.h
  src/storage/common/snapshot_info.cpp
  src/storage/common/snapshot_info.cppm
  src/storage/io/virtual_store.cpp
  src/storage/io/virtual_store.cppm
  src/storage/meta/entry/block_column_entry.cpp
  src/storage/meta/entry/block_column_entry.cppm
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/meta/entry/segment_entry.cpp
  src/storage/meta/entry/segment_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
Labels: ci

#2423 Add snapshot, part3
  CMakeLists.txt
  src/common/utility/utility.cpp
  src/common/utility/utility.cppm
  src/storage/common/snapshot_info.cpp
  src/storage/io/virtual_store.cpp
  src/storage/io/virtual_store.cppm
Labels: ci

#2425 Add snapshot, part4
  src/executor/operator/physical_command.cpp
  src/executor/operator/physical_show.cpp
  src/executor/operator/snapshot/snapshot.cpp
  src/executor/operator/snapshot/snapshot_brief.cpp
  src/executor/operator/snapshot/snapshot_brief.cppm
  src/executor/operator/snapshot/table_snapshot.cpp
  src/storage/common/snapshot_info.cppm
  src/storage/meta/catalog.cpp
  src/storage/meta/catalog.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
  src/storage/txn/txn.cpp
Labels: ci

#2422 Fix data race in MemoryIndexer::Dump
  src/storage/invertedindex/memory_indexer.cpp
Labels: ci, slow-test

#2427 Update version info of release
  CMakeLists.txt
Labels: ci

#2429 More debug log for import CSV
  src/executor/operator/physical_import.cpp
Labels: ci

#2424 Mmap4
  python/test_pysdk/test_knn.py
  src/parser/type/serialize.h
  src/storage/buffer/buffer_handle.cpp
  src/storage/buffer/buffer_obj.cpp
  src/storage/buffer/buffer_obj.cppm
  src/storage/buffer/file_worker/bmp_index_file_worker.cpp
  src/storage/buffer/file_worker/bmp_index_file_worker.cppm
  src/storage/buffer/file_worker/data_file_worker.cpp
  src/storage/buffer/file_worker/data_file_worker.cppm
  src/storage/buffer/file_worker/emvb_index_file_worker.cpp
  src/storage/buffer/file_worker/emvb_index_file_worker.cppm
  src/storage/buffer/file_worker/file_worker.cpp
  src/storage/buffer/file_worker/file_worker.cppm
  src/storage/buffer/file_worker/hnsw_file_worker.cpp
  src/storage/buffer/file_worker/hnsw_file_worker.cppm
  src/storage/buffer/file_worker/ivf_index_file_worker.cpp
  src/storage/buffer/file_worker/ivf_index_file_worker.cppm
  src/storage/buffer/file_worker/raw_file_worker.cpp
  src/storage/buffer/file_worker/raw_file_worker.cppm
  src/storage/buffer/file_worker/secondary_index_file_worker.cpp
  src/storage/buffer/file_worker/secondary_index_file_worker.cppm
  src/storage/buffer/file_worker/var_file_worker.cpp
  src/storage/buffer/file_worker/var_file_worker.cppm
  src/storage/buffer/file_worker/version_file_worker.cpp
  src/storage/buffer/file_worker/version_file_worker.cppm
  src/storage/io/virtual_store.cpp
  src/storage/knn_index/knn_hnsw/abstract_hnsw.cpp
  src/storage/knn_index/knn_hnsw/abstract_hnsw.cppm
  src/storage/knn_index/knn_hnsw/data_store/data_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/data_store_util.cppm
  src/storage/knn_index/knn_hnsw/data_store/graph_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/lvq_vec_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/plain_vec_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/sparse_vec_store.cppm
  src/storage/knn_index/knn_hnsw/data_store/vec_store_type.cppm
  src/storage/knn_index/knn_hnsw/dist_func_cos.cppm
  src/storage/knn_index/knn_hnsw/dist_func_ip.cppm
  src/storage/knn_index/knn_hnsw/dist_func_l2.cppm
  src/storage/knn_index/knn_hnsw/dist_func_sparse_ip.cppm
  src/storage/knn_index/knn_hnsw/hnsw_alg.cppm
  src/storage/knn_index/sparse/bmp_alg.cppm
  src/storage/knn_index/sparse/bmp_fwd.cppm
  src/storage/knn_index/sparse/bmp_ivt.cppm
  src/storage/meta/entry/chunk_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cpp
  src/unit_test/storage/knnindex/knn_hnsw/test_hnsw.cpp
  src/unit_test/storage/knnindex/knn_sparse/test_bmp_fwd.cpp
  src/unit_test/storage/knnindex/knn_sparse/test_bmp_index.cpp
  src/unit_test/storage/knnindex/knn_sparse/test_bmp_ivt.cpp
  test/sql/dql/knn/sparse/test_knn_sparse_bmp.slt
  test/sql/dql/knn/sparse/test_knn_sparse_bmp_realtime.slt
  tools/ci_tools/check_benchmark_result.py
  tools/generate_big_sparse.py
Labels: ci

#2428 Fix checkpoint ts.
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
Labels: ci

#2426 Fix data race in slow test
  src/storage/invertedindex/memory_indexer.cpp
  src/storage/invertedindex/memory_indexer.cppm
  src/storage/meta/entry/block_column_entry.cpp
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/tracer/base_memindex.cppm
  src/storage/txn/txn_store.cpp
  src/storage/txn/txn_store.cppm
  src/storage/wal/wal_manager.cpp
Labels: ci, slow-test

#2431 Fix dump deleted segment index in dump task.
  src/storage/compaction_process.cpp
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/meta/entry/table_index_entry.cppm
Labels: ci

#2434 Fix recover hnsw
  python/restart_test/test_memidx.py
  src/storage/knn_index/knn_hnsw/data_store/lvq_vec_store.cppm
  test/data/config/restart_test/test_memidx/7.toml
Labels: ci

#2430 Add snapshot, part5
  python/restart_test/test_compact.py
  src/executor/operator/physical_command.cpp
  src/storage/common/snapshot_info.cpp
  src/storage/common/snapshot_info.cppm
  src/storage/meta/entry/chunk_index_entry.cpp
  src/storage/meta/entry/chunk_index_entry.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_index_entry.cpp
  src/storage/meta/entry/table_index_entry.cppm
  tools/run_restart_test.py
Labels: ci

#2437 Fix recycle catalog.
  python/restart_test/test_memidx.py
  src/storage/meta/catalog.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/storage/wal/log_file.cpp
  src/storage/wal/log_file.cppm
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
  src/unit_test/storage/wal/recycle_log.cpp
Labels: ci, slow-test

#2435 Fix data race
  src/storage/invertedindex/format/flush_info.cppm
Labels: ci, slow-test

#2440 Fix slow test bugs
  src/executor/operator/physical_limit.cpp
  src/storage/meta/entry/segment_entry.cpp
Labels: ci, slow-test

#2439 Finish table snapshot creation
  src/executor/operator/physical_command.cpp
  src/executor/operator/snapshot/snapshot_brief.cpp
  src/executor/operator/snapshot/table_snapshot.cpp
  src/storage/common/snapshot_info.cpp
  src/storage/meta/entry/block_column_entry.cpp
  src/storage/persistence/persistence_manager.cpp
  src/storage/persistence/persistence_manager.cppm
Labels: ci

#2432 Add truncate function
  python/infinity_embedded/utils.py
  python/infinity_http.py
  python/test_pysdk/common/common_data.py
  python/test_pysdk/test_select.py
  src/common/stl.cppm
  src/function/builtin_functions.cpp
  src/function/scalar/truncate.cpp
  src/function/scalar/truncate.cppm
  src/unit_test/function/scalar/truncate_functions.cpp
Labels: bug, ci

#2450 Fulltext realtime index
  python/restart_test/test_fulltext.py
  src/storage/definition/index_full_text.cpp
  src/storage/definition/index_full_text.cppm
  src/storage/invertedindex/column_inverter.cpp
  src/storage/invertedindex/column_inverter.cppm
  src/storage/invertedindex/format/inmem_doc_list_decoder.cpp
  src/storage/invertedindex/index_defines.cppm
  src/storage/invertedindex/memory_indexer.cpp
  src/storage/invertedindex/memory_indexer.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/segment_index_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn_store.cppm
  src/unit_test/storage/invertedindex/format/inmem_doc_list_decoder.cpp
Labels: ci

#2452 Update HTTP API response data type of integer and float
  python/infinity_http.py
  src/network/http/http_search.cpp
  src/storage/column_vector/value.cpp
  src/storage/column_vector/value.cppm
Labels: ci

#2449 Add Reverse Function
  python/test_pysdk/test_select.py
  src/function/builtin_functions.cpp
  src/function/scalar/reverse.cpp
  src/function/scalar/reverse.cppm
  src/unit_test/function/scalar/reverse_functions.cpp
  test/sql/dql/type/truncate.slt
  test/sql/dql/type/varchar.slt
Labels: ci

#2459 Update version to 0.6.0-dev2 and use lts-polars-cpu as the pandas module
  README.md
  benchmark/remote_infinity/remote_query_benchmark.cpp
  client/cpp/infinity_client.cpp
  docs/getstarted/build_from_source.mdx
  docs/getstarted/deploy_infinity_server.mdx
  docs/getstarted/quickstart.md
  example/README.md
  pyproject.toml
  python/infinity_sdk/README.md
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/pyproject.toml
  python/requirements.txt
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
Labels: ci

#2461 Add more information on transaction history
  src/executor/operator/physical_show.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn_context.cpp
  src/storage/txn/txn_context.cppm
Labels: ci

#2462 Enable doc payload for inverted index
  src/common/analyzer/analyzer.cppm
  src/common/analyzer/common_analyzer.cpp
  src/common/analyzer/common_analyzer.cppm
  src/common/analyzer/ik/ik_analyzer.cpp
  src/common/analyzer/ngram_analyzer.cpp
  src/common/analyzer/rag_analyzer.cpp
  src/common/analyzer/term.cpp
  src/common/analyzer/term.cppm
  src/common/analyzer/whitespace_analyzer.cpp
  src/storage/invertedindex/column_inverter.cpp
  src/storage/invertedindex/column_inverter.cppm
  src/storage/invertedindex/common/external_sort_merger.cpp
  src/storage/invertedindex/common/external_sort_merger.cppm
  src/storage/invertedindex/memory_indexer.cpp
  src/storage/invertedindex/search/search_driver.cpp
  src/unit_test/storage/invertedindex/common/external_sort.cpp
Labels: ci

#2458 Add some Datetime Function
  python/test_pysdk/test_select.py
  src/function/builtin_functions.cpp
  src/function/scalar/day.cpp
  src/function/scalar/day.cppm
  src/function/scalar/hour.cpp
  src/function/scalar/hour.cppm
  src/function/scalar/minute.cpp
  src/function/scalar/minute.cppm
  src/function/scalar/month.cpp
  src/function/scalar/month.cppm
  src/function/scalar/second.cpp
  src/function/scalar/second.cppm
  src/function/scalar/year.cpp
  src/function/scalar/year.cppm
  src/parser/parser.cpp
  src/parser/parser.y
  src/unit_test/function/scalar/day_functions.cpp
  src/unit_test/function/scalar/hour_functions.cpp
  src/unit_test/function/scalar/minute_function.cpp
  src/unit_test/function/scalar/month_functions.cpp
  src/unit_test/function/scalar/second_function.cpp
  src/unit_test/function/scalar/year_functions.cpp
  test/sql/dql/type/datetime_function.slt
Labels: ci

#2463 Refactor txn_type
  src/executor/operator/physical_show.cpp
  src/main/query_context.cpp
  src/storage/compaction_process.cpp
  src/storage/storage.cpp
  src/storage/tracer/memindex_tracer.cpp
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/storage/txn/txn_context.cppm
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
  src/storage/txn/txn_state.cppm
  src/storage/wal/wal_manager.cpp
  src/unit_test/storage/bg_task/cleanup_task.cpp
  src/unit_test/storage/bg_task/compact_segments_task.cpp
  src/unit_test/storage/binary_fuse_filter/segment_sealing.cpp
  src/unit_test/storage/buffer/buffer_obj.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
  src/unit_test/storage/knnindex/merge_optimize/test_optimize.cpp
  src/unit_test/storage/meta/catalog.cpp
  src/unit_test/storage/meta/db_meta.cpp
  src/unit_test/storage/meta/entry/db_entry.cpp
  src/unit_test/storage/meta/entry/segment_entry.cpp
  src/unit_test/storage/meta/entry/segment_index_entry.cpp
  src/unit_test/storage/meta/entry/table_collection_entry.cpp
  src/unit_test/storage/meta/entry/table_entry.cpp
  src/unit_test/storage/meta/entry/table_index_entry.cpp
  src/unit_test/storage/meta/table_index_meta.cpp
  src/unit_test/storage/meta/table_meta.cpp
  src/unit_test/storage/txn/conflict_check.cpp
  src/unit_test/storage/txn/database_txn.cpp
  src/unit_test/storage/txn/table_txn.cpp
  src/unit_test/storage/wal/catalog_delta_replay.cpp
  src/unit_test/storage/wal/checkpoint.cpp
  src/unit_test/storage/wal/recycle_log.cpp
  src/unit_test/storage/wal/repeat_replay.cpp
  src/unit_test/storage/wal/wal_replay.cpp
  tools/run_restart_test.py
Labels: ci

#2466 Support array type: part 2
  src/executor/operator/physical_export.cpp
  src/executor/operator/physical_export.cppm
  src/parser/type/info/array_info.h
  src/parser/type/internal_types.h
  src/storage/column_vector/column_vector.cpp
  src/storage/column_vector/column_vector.cppm
  src/storage/column_vector/value.cpp
  src/storage/column_vector/value.cppm
  src/storage/column_vector/vector_buffer.cpp
  src/storage/column_vector/vector_buffer.cppm
Labels: ci

#2443 Restore table snapshot, part1
  client/cpp/infinity_client.h
  src/common/status.cpp
  src/common/status.cppm
  src/embedded_infinity_ext.cpp
  src/executor/operator/physical_command.cpp
  src/executor/operator/snapshot/snapshot.cppm
  src/executor/operator/snapshot/table_snapshot.cpp
  src/storage/common/snapshot_info.cpp
  src/storage/common/snapshot_info.cppm
  src/storage/meta/catalog.cpp
  src/storage/meta/catalog.cppm
  src/storage/meta/entry/block_column_entry.cpp
  src/storage/meta/entry/block_column_entry.cppm
  src/storage/meta/entry/block_entry.cpp
  src/storage/meta/entry/block_entry.cppm
  src/storage/meta/entry/db_entry.cpp
  src/storage/meta/entry/db_entry.cppm
  src/storage/meta/entry/entry_list.cppm
  src/storage/meta/entry/segment_entry.cpp
  src/storage/meta/entry/segment_entry.cppm
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/entry/table_entry.cppm
  src/storage/meta/table_meta.cpp
  src/storage/meta/table_meta.cppm
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
Labels: ci

#2469 Use txn but not WAL entry in WAL flush thread
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
Labels: ci

#2468 Refactor transaction commit
  src/main/query_context.cpp
  src/main/query_context.cppm
  src/storage/txn/txn.cpp
  src/storage/txn/txn.cppm
  src/storage/txn/txn_manager.cpp
  src/unit_test/test_helper/sql_runner.cpp
Labels: ci

#2472 Refactor checkpoint and fix UT
  src/bin/infinity_main.cpp
  src/common/status.cpp
  src/common/status.cppm
  src/main/infinity.cpp
  src/main/infinity_context.cpp
  src/main/infinity_context.cppm
  src/main/query_context.cpp
  src/storage/background_process.cpp
  src/storage/buffer/buffer_obj.cpp
  src/storage/txn/txn_manager.cpp
  src/storage/txn/txn_manager.cppm
  src/storage/wal/wal_manager.cpp
  src/unit_test/storage/wal/checkpoint.cpp
Labels: ci

#2467 Add DayOfYear, DayOfMonth, DayOfWeek Functions
  python/test_pysdk/test_select.py
  src/function/builtin_functions.cpp
  src/function/scalar/day_of_month.cpp
  src/function/scalar/day_of_month.cppm
  src/function/scalar/day_of_week.cpp
  src/function/scalar/day_of_week.cppm
  src/function/scalar/day_of_year.cpp
  src/function/scalar/day_of_year.cppm
  src/parser/type/datetime/date_type.cpp
  src/parser/type/datetime/date_type.h
  src/parser/type/datetime/date_type_std.cpp
  src/parser/type/datetime/date_type_std.h
  src/parser/type/datetime/datetime_type.cpp
  src/parser/type/datetime/datetime_type.h
  src/unit_test/function/scalar/day_of_month_functions.cpp
  src/unit_test/function/scalar/day_of_week.cpp
  src/unit_test/function/scalar/day_of_year_functions.cpp
  test/sql/dql/type/datetime_function.slt
Labels: ci

#2475 Fix memory leak
  src/storage/knn_index/knn_ivf/ivf_index_data_in_mem.cpp
Labels: ci

#2479 Fix duplicated WAL file issue
  src/storage/wal/wal_manager.cpp
  src/storage/wal/wal_manager.cppm
  src/unit_test/storage/wal/recycle_log.cpp
  test/data/config/test_close_ckp.toml
  test/data/config/test_close_ckp_vfs_off.toml
Labels: ci

#2478 Lsg docs
  docs/references/pysdk_api_reference.md
  src/storage/definition/index_base.cpp
  src/storage/definition/index_hnsw.cpp
  src/storage/definition/index_hnsw.cppm
  src/storage/knn_index/knn_hnsw/hnsw_lsg_builder.cpp
  src/storage/knn_index/knn_hnsw/hnsw_lsg_builder.cppm
  src/storage/meta/entry/segment_index_entry.cpp
  src/unit_test/storage/knnindex/knn_hnsw/test_lsg_build.cpp
  test/sql/dql/knn/embedding/test_knn_hnsw_l2_lsg.slt
Labels: documentation, ci

#2477 Add Other Datetime Functions
  python/test_pysdk/test_select.py
  src/function/builtin_functions.cpp
  src/function/scalar/century.cpp
  src/function/scalar/century.cppm
  src/function/scalar/date_part.cpp
  src/function/scalar/date_part.cppm
  src/function/scalar/epoch.cpp
  src/function/scalar/epoch.cppm
  src/function/scalar/era.cpp
  src/function/scalar/era.cppm
  src/function/scalar/quarter.cpp
  src/function/scalar/quarter.cppm
  src/function/scalar/week_of_year.cpp
  src/function/scalar/week_of_year.cppm
  src/function/scalar/weekday.cpp
  src/function/scalar/weekday.cppm
  src/parser/type/datetime/date_type.cpp
  src/parser/type/datetime/date_type.h
  src/parser/type/datetime/date_type_std.cpp
  src/parser/type/datetime/date_type_std.h
  src/unit_test/function/scalar/century_functions.cpp
  src/unit_test/function/scalar/date_part_functions.cpp
  src/unit_test/function/scalar/epoch_functions.cpp
  src/unit_test/function/scalar/era_functions.cpp
  src/unit_test/function/scalar/quarter_functions.cpp
  src/unit_test/function/scalar/week_of_year_functions.cpp
  src/unit_test/function/scalar/weekday_functions.cpp
  test/sql/dql/type/datetime_function.slt
Labels: ci

#2482 Add delete file log
  src/executor/operator/snapshot/snapshot.cpp
  src/storage/buffer/file_worker/file_worker.cpp
  src/storage/invertedindex/column_index_merger.cpp
  src/storage/invertedindex/memory_indexer.cpp
  src/storage/io/virtual_store.cpp
  src/storage/knn_index/knn_diskann/diskann_index_data.cppm
  src/storage/meta/entry/chunk_index_entry.cpp
  src/storage/wal/log_file.cpp
  src/storage/wal/wal_entry.cpp
  src/storage/wal/wal_manager.cpp
Labels: ci

#2483 Fix no snapshot trigger core dump
  src/executor/operator/snapshot/table_snapshot.cpp
Labels: ci

#2484 Refactor GetCleanupScanTS
  src/storage/txn/txn_manager.cpp
Labels: ci

#2488 Group by 1
  src/executor/hash_table.cpp
  src/executor/hash_table.cppm
  src/executor/operator/physical_aggregate.cpp
  src/executor/operator/physical_aggregate.cppm
  src/executor/operator/physical_merge_aggregate.cpp
  src/executor/operator/physical_merge_aggregate.cppm
  src/executor/operator_state.cppm
  src/storage/data_block.cpp
  src/storage/data_table.cpp
  src/storage/data_table.cppm
  test/sql/dql/aggregate/test_groupby_aggtype.slt
  test/sql/dql/aggregate/test_groupby_complex.slt
  test/sql/dql/aggregate/test_groupby_datatype.slt
  tools/generate_groupby1.py
  tools/sqllogictest.py
Labels: ci

#2487 Support rank features query:part1
  src/common/analyzer/analyzer.cppm
  src/common/analyzer/analyzer_pool.cpp
  src/common/analyzer/analyzer_pool.cppm
  src/common/analyzer/common_analyzer.cpp
  src/common/analyzer/ik/ik_analyzer.cpp
  src/common/analyzer/ngram_analyzer.cpp
  src/common/analyzer/rag_analyzer.cpp
  src/common/analyzer/rank_features_analyzer.cpp
  src/common/analyzer/rank_features_analyzer.cppm
  src/common/analyzer/term.cppm
  src/common/analyzer/whitespace_analyzer.cpp
  src/executor/operator/physical_match.cpp
  src/executor/operator/physical_match.cppm
  src/executor/physical_planner.cpp
  src/planner/bound_select_statement.cpp
  src/planner/node/logical_match.cppm
  src/planner/optimizer/index_scan/index_filter_evaluators.cppm
  src/storage/invertedindex/search/doc_iterator.cppm
  src/storage/invertedindex/search/parse_fulltext_options.cpp
  src/storage/invertedindex/search/parse_fulltext_options.cppm
  src/storage/invertedindex/search/query_builder.cpp
  src/storage/invertedindex/search/query_builder.cppm
  src/storage/invertedindex/search/query_node.cpp
  src/storage/invertedindex/search/query_node.h
  src/storage/invertedindex/search/rank_feature_doc_iterator.cpp
  src/storage/invertedindex/search/rank_feature_doc_iterator.cppm
  src/storage/invertedindex/search/rank_features_doc_iterator.cpp
  src/storage/invertedindex/search/rank_features_doc_iterator.cppm
  src/unit_test/storage/invertedindex/search/query_builder.cpp
  src/unit_test/storage/invertedindex/search/query_match.cpp
Labels: ci

#2485 Fix restore meet duplicated table entry
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
  src/storage/meta/table_meta.cpp
Labels: ci

#2492 Add python support for Array
  python/infinity_embedded/common.py
  python/infinity_embedded/local_infinity/types.py
  python/infinity_embedded/local_infinity/utils.py
  python/infinity_sdk/infinity/common.py
  python/infinity_sdk/infinity/remote_thrift/infinity_thrift_rpc/ttypes.py
  python/infinity_sdk/infinity/remote_thrift/types.py
  python/infinity_sdk/infinity/remote_thrift/utils.py
  python/test_pysdk/test_insert.py
  src/embedded_infinity/wrap_infinity.cpp
  src/embedded_infinity/wrap_infinity.cppm
  src/embedded_infinity_ext.cpp
  src/network/infinity_thrift/infinity_types.cpp
  src/network/infinity_thrift/infinity_types.h
  src/network/infinity_thrift_service.cpp
  src/network/infinity_thrift_service.cppm
  src/network/infinity_thrift_types.cppm
  src/storage/column_vector/vector_buffer.cpp
  thrift/infinity.thrift
Labels: ci

#2491 Groupby2
  docs/references/http_api_reference.mdx
  docs/references/pysdk_api_reference.md
  python/infinity_embedded/local_infinity/query_builder.py
  python/infinity_embedded/local_infinity/table.py
  python/infinity_embedded/local_infinity/utils.py
  python/infinity_http.py
  python/infinity_sdk/infinity/remote_thrift/query_builder.py
  python/infinity_sdk/infinity/remote_thrift/table.py
  python/infinity_sdk/infinity/remote_thrift/utils.py
  python/test_pysdk/common/common_data.py
  python/test_pysdk/test_groupby.py
  src/embedded_infinity/wrap_infinity.cpp
  src/embedded_infinity/wrap_infinity.cppm
  src/embedded_infinity_ext.cpp
  src/executor/operator/physical_aggregate.cpp
  src/network/http/http_search.cpp
  src/network/infinity_thrift_service.cpp
  src/planner/binder/order_binder.cpp
  test/sql/dql/aggregate/test_groupby_aggtype.slt
  test/sql/dql/aggregate/test_groupby_complex.slt
Labels: documentation, ci

#2493 Groupby3
  benchmark/local_infinity/knn/knn_query_benchmark.cpp
  docs/references/http_api_reference.mdx
  docs/references/pysdk_api_reference.md
  python/infinity_embedded/local_infinity/client.py
  python/infinity_embedded/local_infinity/query_builder.py
  python/infinity_embedded/local_infinity/table.py
  python/infinity_http.py
  python/infinity_sdk/infinity/remote_thrift/client.py
  python/infinity_sdk/infinity/remote_thrift/query_builder.py
  python/infinity_sdk/infinity/remote_thrift/table.py
  python/test_pysdk/test_groupby.py
  src/embedded_infinity/wrap_infinity.cpp
  src/embedded_infinity/wrap_infinity.cppm
  src/embedded_infinity_ext.cpp
  src/main/infinity.cpp
  src/main/infinity.cppm
  src/network/http/http_search.cpp
  src/network/infinity_thrift_service.cpp
  src/unit_test/main/infinity.cpp
  src/unit_test/main/table.cpp
  test/sql/dql/aggregate/test_groupby_complex.slt
Labels: documentation, ci

#2494 Update http support for Array
  example/http/insert_search_data.sh
  src/executor/operator/physical_import.cpp
  src/network/http_server.cpp
  src/parser/expr/constant_expr.cpp
  src/parser/expr/constant_expr.h
Labels: ci

#2495 Update doc for Array
  docs/references/http_api_reference.mdx
  docs/references/pysdk_api_reference.md
Labels: ci

#2496 Add check for creating array type in python sdk
  python/infinity_embedded/local_infinity/utils.py
  python/infinity_sdk/infinity/remote_thrift/utils.py
  python/test_pysdk/test_insert.py
  src/storage/meta/entry/segment_index_entry.cpp
Labels: ci

#2497 Fix taskletcount
  src/executor/operator/physical_aggregate.cppm
  src/executor/operator/physical_alter.cppm
  src/executor/operator/physical_command.cpp
  src/executor/operator/physical_command.cppm
  src/executor/operator/physical_compact_finish.cppm
  src/executor/operator/physical_compact_index_prepare.cpp
  src/executor/operator/physical_compact_index_prepare.cppm
  src/executor/operator/physical_create_collection.cppm
  src/executor/operator/physical_create_index_finish.cppm
  src/executor/operator/physical_create_index_prepare.cppm
  src/executor/operator/physical_create_schema.cppm
  src/executor/operator/physical_create_table.cppm
  src/executor/operator/physical_create_view.cppm
  src/executor/operator/physical_cross_product.cppm
  src/executor/operator/physical_delete.cppm
  src/executor/operator/physical_drop_collection.cppm
  src/executor/operator/physical_drop_index.cppm
  src/executor/operator/physical_drop_schema.cppm
  src/executor/operator/physical_drop_table.cppm
  src/executor/operator/physical_drop_view.cppm
  src/executor/operator/physical_dummy_operator.cppm
  src/executor/operator/physical_dummy_scan.cppm
  src/executor/operator/physical_except.cppm
  src/executor/operator/physical_explain.cppm
  src/executor/operator/physical_export.cppm
  src/executor/operator/physical_flush.cppm
  src/executor/operator/physical_hash.cppm
  src/executor/operator/physical_hash_join.cppm
  src/executor/operator/physical_import.cppm
  src/executor/operator/physical_index_join.cppm
  src/executor/operator/physical_insert.cppm
  src/executor/operator/physical_intersect.cppm
  src/executor/operator/physical_merge_aggregate.cppm
  src/executor/operator/physical_merge_hash.cppm
  src/executor/operator/physical_merge_limit.cppm
  src/executor/operator/physical_merge_parallel_aggregate.cppm
  src/executor/operator/physical_merge_sort.cppm
  src/executor/operator/physical_nested_loop_join.cppm
  src/executor/operator/physical_optimize.cppm
  src/executor/operator/physical_parallel_aggregate.cppm
  src/executor/operator/physical_prepared_plan.cppm
  src/executor/operator/physical_scan/physical_merge_knn.cppm
  src/executor/operator/physical_show.cppm
  src/executor/operator/physical_sink.cppm
  src/executor/operator/physical_sort_merge_join.cppm
  src/executor/operator/physical_source.cppm
  src/executor/operator/physical_union_all.cppm
  src/executor/operator/physical_update.cppm
  src/executor/physical_operator.cpp
  src/executor/physical_operator.cppm
  src/scheduler/fragment_context.cpp
  test/sql/dql/knn/embedding/test_knn_hnsw_l2.slt
Labels: ci

#2498 Fix compile
  benchmark/local_infinity/fulltext/fulltext_benchmark.cpp
  benchmark/local_infinity/infinity_benchmark.cpp
Labels: ci

#2499 Fix: exception in OptimizeIndex
  src/storage/meta/entry/segment_index_entry.cpp
  src/storage/meta/entry/table_entry.cpp
Labels: ci

#2501 Unnest1
  src/executor/operator/physical_unnest.cpp
  src/executor/operator/physical_unnest.cppm
  src/expression/column_expression.cppm
  src/expression/expression_type.cppm
  src/expression/unnest_expression.cpp
  src/expression/unnest_expression.cppm
  src/parser/lexer.cpp
  src/parser/lexer.h
  src/parser/lexer.l
  src/parser/parser.cpp
  src/parser/parser.h
  src/parser/parser.y
  src/parser/statement/select_statement.cpp
  src/parser/statement/select_statement.h
  src/planner/bind_context.cppm
  src/planner/binder/project_binder.cpp
  src/planner/binder/project_binder.cppm
  src/planner/binder/unnest_binder.cpp
  src/planner/binder/unnest_binder.cppm
  src/planner/bound_select_statement.cpp
  src/planner/explain_ast.cpp
  src/planner/logical_node_visitor.cpp
  src/planner/logical_node_visitor.cppm
  src/planner/node/logical_unnest.cpp
  src/planner/node/logical_unnest.cppm
  src/planner/optimizer/column_pruner.cpp
  src/planner/optimizer/lazy_load.cpp
  src/planner/query_binder.cpp
  test/sql/dql/unnest/test_unnest.slt
Labels: ci
